const schedules = {

  // PALINSESTO SETTIMANALE COMPLETO - ARS EUROPA TV
// Domenica (0) e Sabato (6) già presenti nel file originale.
// Di seguito i cinque giorni mancanti: Lunedì (1), Martedì (2), Mercoledì (3), Giovedì (4), Venerdì (5).

0: [ // DOMENICA - massima variazione di genere
  { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio trasmissioni", tag: "ARS EUROPA TV" },
  { time: "08:02", id: "dyHRAo_bOjA", title: "Né Apocalittici né Integrati - Prima puntata - la terza via dell'Intelligenza Artificiale", tag: "Semiotica Intelligenza Artificiale" },
  { time: "08:20", id: "ElM7rPK06k8", title: "Decameron - Come mandare il diavolo all'inferno - III giornata X novella", tag: "Decameron" },
  { time: "08:31", id: "FyYCrzZPETI", title: "Inferno - Canto XI - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "08:45", id: "UU9BLVei6QU", title: "L'occhio di Horus - Antico Egitto - Semeion", tag: "Semeion" },
  { time: "08:59", id: "MDQGHFNb4Yg", title: "Paul Cézanne - Natura morta con pesche e pere", tag: "Arte & Simboli" },
  { time: "09:07", id: "1JTtwMU3W4c", title: "Cyrano de Bergerac - Edmond Rostand, Non, merci", tag: "Letteratura" },
  { time: "09:15", id: "zOEB44h7S5k", title: "Medea - Euripide - Gli Immortali", tag: "Teatro Greco" },
  { time: "09:35", id: "jNGOdGlE7LQ", title: "La Lupa - I simboli e la storia di Roma", tag: "Mitologia" },
  { time: "09:43", id: "YDGpLW-lSrc", title: "Madian e i 300 di Gedeone - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "09:58", id: "bYT2Ok4r8qI", title: "Catullo - Dammi mille baci - Carme V", tag: "Poesia" },
  { time: "10:02", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria - I presocratici - Philosophia", tag: "Filosofia" },
  { time: "10:10", id: "2eNrA0pvehA", title: "La sedia - Sign&Design - 1ª puntata", tag: "Design" },
  { time: "10:48", id: "bVVeeRVkKAE", title: "Montale e il male di vivere - profeta del nostro presente", tag: "I principi della poesia" },
  { time: "11:18", id: "7Y3g-9sAX2g", title: "Il segno del comando nell'Antica Roma", tag: "Storia" },
  { time: "11:26", id: "M3SAVcBKSW4", title: "Marco, il leone del deserto - Tetramorfo", tag: "Tetramorfo" },
  { time: "11:35", id: "ukXAsImHyDU", title: "Polisemantica - Il mondo in un segno - 2ª puntata", tag: "Semiotica" },
  { time: "11:45", id: "hboGN6-AvYo", title: "Né Apocalittici né Integrati - Seconda puntata - Simnoesi, pensare insieme, oltre lo specchio", tag: "Semiotica Intelligenza Artificiale" },
  { time: "12:00", id: "8tkD5HhoxYM", title: "Decameron - Chichibìo e la gru - VI giornata IV novella", tag: "Decameron" },
  { time: "12:09", id: "kjDXf0ndIWY", title: "Inferno - Canto XII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "12:26", id: "H4YXia6yz-E", title: "Vita medievale - Semeion - 4ª puntata", tag: "Semeion" },
  { time: "13:01", id: "xKRU6UqRLTQ", title: "Simbologia del Corteo dei Magi - Benozzo Gozzoli", tag: "Arte & Simboli" },
  { time: "13:20", id: "U5HuJnOl12s", title: "I consigli di Ovidio - il trucco femminile - Ars Amandi", tag: "Letteratura" },
  { time: "13:27", id: "uaSEfOUDRDo", title: "Edipo Re - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "13:48", id: "NGY1ZCjtirA", title: "L'egida, la capra Amaltea e la cornucopia - Mitologia", tag: "Mitologia" },
  { time: "13:55", id: "EUKj2MyULiw", title: "Apocalisse: le ultime parole di Dio", tag: "Sacrum" },
  { time: "14:45", id: "4lD4LRrAHL8", title: "Cecco Angiolieri - S'i' fosse foco", tag: "Poesia" },
  { time: "14:49", id: "1zSwyFPn4Yk", title: "Socrate - Philosophia", tag: "Filosofia" },
  { time: "14:58", id: "q8-VMJW1r80", title: "Il tavolo - Sign&Design - 2ª puntata", tag: "Design" },
  { time: "15:27", id: "7PHWv12rfXM", title: "Salvatore Quasimodo - gli elementi della creazione", tag: "I principi della poesia" },
  { time: "15:55", id: "_n092qNIw7o", title: "La simbologia dello Scarabeo sacro nell'Antico Egitto", tag: "Storia" },
  { time: "16:07", id: "T6_0Hzog4x0", title: "Luca, lo scriba della mansuetudine - Tetramorfo", tag: "Tetramorfo" },
  { time: "16:20", id: "c4U77oicbuU", title: "Polisemantica - Il mondo in un segno - 3ª puntata", tag: "Semiotica" },
  { time: "16:30", id: "9jSQdHofi5c", title: "Né Apocalittici né Integrati - Terza puntata - L'Emittente nascosto", tag: "Semiotica Intelligenza Artificiale" },
  { time: "16:47", id: "T9m9cm0dhWY", title: "Decameron - Come attaccare la coda a una cavalla - IX giornata X novella", tag: "Decameron" },
  { time: "16:59", id: "-_OiF7-GR0Q", title: "Inferno - Canto XIII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "17:13", id: "mwSAxNQ_re0", title: "Società dell'antica Roma - Semeion - 5ª puntata", tag: "Semeion" },
  { time: "17:52", id: "H9XFulxh-2Q", title: "Giotto - Maestà di Ognissanti - Uffizi", tag: "Arte & Simboli" },
  { time: "18:35", id: "JIDwzu-phUo", title: "I consigli di Marco Aurelio - la cooperazione", tag: "Letteratura" },
  { time: "18:42", id: "4O8X48ICIaw", title: "I sette contro Tebe - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "19:06", id: "59mof2mvVaw", title: "Simbologia di Ercole e Anteo - Pollaiolo", tag: "Mitologia" },
  { time: "19:29", id: "jeHmaJmp3wg", title: "Nehusthan, il serpente di bronzo - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "19:37", id: "xGA5AEx0HdQ", title: "Ugo Foscolo - Alla sera", tag: "Poesia" },
  { time: "19:41", id: "5coSTdhVpuU", title: "Platone - Philosophia", tag: "Filosofia" },
  { time: "19:54", id: "dly0X-1e3bo", title: "Il letto - Sign&Design - 3ª puntata", tag: "Design" },
  { time: "20:28", id: "UUSpcCJPgA8", title: "Giuseppe Ungaretti - i punti cardinali dell'ispirazione", tag: "I principi della poesia" },
  { time: "21:41", id: "xLiWCB2m9Jg", title: "I simboli sacerdotali nell'antica Roma", tag: "Storia" },
  { time: "21:52", id: "KIPYOCWYVSU", title: "Giovanni, lo sguardo dell'aquila - Tetramorfo", tag: "Tetramorfo" },
  { time: "22:08", id: "9K_bfj937Pg", title: "Decameron - Un mercante ebreo in Vaticano - I giornata II novella", tag: "Decameron" },
  { time: "22:20", id: "fdy6LJOROCI", title: "Inferno - Canto XIV - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "22:33", id: "hPWQR2BU49Y", title: "Religioni del Mediterraneo - Semeion - 6ª puntata", tag: "Semeion" },
  { time: "23:07", id: "91IGWNwcUAU", title: "Simbologia della Deposizione - Caravaggio", tag: "Arte & Simboli" },
  { time: "23:25", id: "4JhzDRygmAI", title: "I consigli di Cicerone - il valore dell'amicizia", tag: "Letteratura" },
  { time: "23:32", id: "9wxNflU3IFQ", title: "I Persiani - Eschilo - Gli Immortali", tag: "Teatro Greco" },
],
1: [ // LUNEDÌ - massima variazione di genere
  { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio trasmissioni", tag: "ARS EUROPA TV" },
  { time: "08:02", id: "egeEdEQFkT8", title: "Decameron - Il monaco e l'abate - I giornata IV novella", tag: "Decameron" },
  { time: "08:14", id: "p-GGCkdDG7o", title: "Inferno - Canto XV - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "08:26", id: "eX13aqoGOqU", title: "Il mito dei Fenici - Semeion - 7ª puntata", tag: "Semeion" },
  { time: "09:01", id: "md0SomPZXx0", title: "Leonardo da Vinci - Adorazione dei Magi", tag: "Arte & Simboli" },
  { time: "09:19", id: "jtStIm5z7II", title: "I consigli di Seneca - Amicizia", tag: "Letteratura" },
  { time: "09:26", id: "gYZlbiG0Mk4", title: "Edipo a Colono - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "10:16", id: "-kT2WSjxw20", title: "L'ulivo, la civetta e il serpente - I Simboli e la Storia", tag: "Mitologia" },
  { time: "10:24", id: "_AHY1IOE1Hg", title: "I Demoni - Sacrum, i simboli nelle religioni", tag: "Sacrum" },
  { time: "10:54", id: "HQqdZ18-UHA", title: "Giacomo Leopardi - L'Infinito", tag: "Poesia" },
  { time: "10:58", id: "oqTUTClIW2I", title: "Aristotele - Philosophia", tag: "Filosofia" },
  { time: "11:07", id: "LTmiNv4V0FM", title: "La lampada nell'Arte", tag: "Design" },
  { time: "11:19", id: "s6QnfgVPxZA", title: "I simboli dell'alchimia nel Medioevo", tag: "Storia" },
  { time: "11:27", id: "h88VDynvAs0", title: "Decameron - Maestro Alberto e il porro - I giornata X novella", tag: "Decameron" },
  { time: "11:36", id: "dKTmwGpxC9g", title: "Inferno - Canto XVII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "11:50", id: "IjEmsqnsHKY", title: "L'invincibile esercito romano - Semeion", tag: "Semeion" },
  { time: "12:22", id: "zoeXahpnNBA", title: "Maestro Venceslao - Novembre nel Ciclo dei Mesi di Torre Aquila", tag: "Arte & Simboli" },
  { time: "12:37", id: "0Q3UHX75roM", title: "I consigli di Agostino - la felicità - le Confessioni", tag: "Letteratura" },
  { time: "12:44", id: "LBdvcDAlFjM", title: "Filottete - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "13:17", id: "8RHc0dwAVmE", title: "Orfeo - Simboli, miti e leggende", tag: "Mitologia" },
  { time: "13:34", id: "J47HGIAt7H0", title: "Giosuè ferma il sole - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "13:42", id: "tgaxKfngNCY", title: "Alessandro Manzoni - Sentir e meditar", tag: "Poesia" },
  { time: "13:46", id: "QcN8IL5cGiI", title: "Crisippo e lo Stoicismo - Philosophia", tag: "Filosofia" },
  { time: "13:59", id: "Gqmjecp3NTo", title: "La lampada e la Storia", tag: "Design" },
  { time: "14:09", id: "_57OfZukJTs", title: "Decameron - Il Sultano Saladino e i tre anelli - I giornata III novella", tag: "Decameron" },
  { time: "14:20", id: "3dRCGVNCmEo", title: "Inferno - Canto XVIII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "14:33", id: "g6kgO00YunM", title: "Simbologia della Cena in Emmaus - Caravaggio", tag: "Arte & Simboli" },
  { time: "14:54", id: "Y9ztKw9W1Sw", title: "I consigli di Platone - l'anima - Fedone", tag: "Letteratura" },
  { time: "15:00", id: "_YN4KrZiSjM", title: "Le Trachinie - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "15:29", id: "0UOJdSzhFrI", title: "Teti - Simboli, miti e leggende", tag: "Mitologia" },
  { time: "15:49", id: "a_sJka5SgjI", title: "Il dono di re Salomone - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "15:57", id: "vGut7h5Wlwc", title: "Orazio - Carpe Diem, afferra l'attimo", tag: "Poesia" },
  { time: "16:01", id: "Pkmfnn3KcWM", title: "Talete e l'acqua - I presocratici - Philosophia", tag: "Filosofia" },
  { time: "16:11", id: "49NaNWgpT9c", title: "La lampada e la sua simbologia", tag: "Design" },
  { time: "16:19", id: "Vjes7xPZgo0", title: "Decameron - Calandrino incinto - IX giornata III novella", tag: "Decameron" },
  { time: "16:31", id: "npJLE6PpIYU", title: "Inferno - Canto VI - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "16:43", id: "55aKom1mDB0", title: "Giovan Francesco Barbieri detto Il Guercino - L'angelo custode", tag: "Arte & Simboli" },
  { time: "16:55", id: "j-QqaWgK3rA", title: "I consigli di Marco Aurelio - Il giusto atteggiamento", tag: "Letteratura" },
  { time: "17:01", id: "VzG3biTZ1rg", title: "Agamennone - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "17:17", id: "1zXxvYDhG4o", title: "Psiche - Simboli, miti e leggende", tag: "Mitologia" },
  { time: "17:35", id: "BLDB2zuKUhA", title: "Eliseo, la vedova e l'olio - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "17:42", id: "S80kNQbbpNk", title: "Anassimandro e l'apeiron - Philosophia", tag: "Filosofia" },
  { time: "17:53", id: "GuO9M2C4R-4", title: "La lampada e il design", tag: "Design" },
  { time: "18:00", id: "TjARMj13bPE", title: "Decameron - Il corsaro Landolfo e la cassetta", tag: "Decameron" },
  { time: "18:09", id: "FSYp-TK2qEk", title: "Inferno - Canto VIII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "18:20", id: "5ice597_aGU", title: "Antonello da Messina - Crocifissione di Sibiu", tag: "Arte & Simboli" },
  { time: "18:38", id: "vtJGNqiVUho", title: "Ippolito - Euripide - Gli Immortali", tag: "Teatro Greco" },
  { time: "19:28", id: "hU_Bq30AsNM", title: "Europa - Simboli, miti e leggende", tag: "Mitologia" },
  { time: "19:38", id: "CJIyeaOe1M8", title: "I simboli sacri nel Medioevo", tag: "Sacrum" },
  { time: "19:47", id: "MAx6zDUILbQ", title: "Zenone e i suoi paradossi - Philosophia", tag: "Filosofia" },
  { time: "19:58", id: "aWlHf7nx3Z8", title: "Decameron - San Giuliano, il mercante e la vedovella", tag: "Decameron" },
  { time: "20:07", id: "ALRIE9NezPQ", title: "Inferno - Canto IX - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "20:20", id: "05RV29HXOI8", title: "Significati nascosti nello Sposalizio della Vergine - Raffaello", tag: "Arte & Simboli" },
  { time: "20:35", id: "VNx-F7naSK0", title: "Elettra - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "21:13", id: "33LYXRz6E5s", title: "Adone - Simboli, miti e leggende", tag: "Mitologia" },
  { time: "21:23", id: "TvY6zNfDhqo", title: "Debora e l'incontro di Sisara e Giaele - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "21:31", id: "5BJaK2Nv3L0", title: "Empedocle e i quattro elementi - Philosophia", tag: "Filosofia" },
  { time: "21:40", id: "9e4uCJAmljA", title: "Decameron - La dama di Guascogna e il re di Cipro", tag: "Decameron" },
  { time: "21:45", id: "axRWC-PjjlI", title: "Inferno - Canto X - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "21:57", id: "I9bfxWuUPSY", title: "Simbologia della Madonna della Seggiola - Raffaello", tag: "Arte & Simboli" },
  { time: "22:16", id: "JxHiv1EbEXY", title: "Aiace - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "23:00", id: "abUpEQBf1b0", title: "Mene, Tekel, Peres - la mano fantasma - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "23:10", id: "KvpEM4bgfZY", title: "Anassagora e il Nous - Philosophia", tag: "Filosofia" },
  { time: "23:20", id: "5D0qcufRzOw", title: "Decameron - Bergamino e l'avarizia di Cangrande", tag: "Decameron" },
  { time: "23:32", id: "-bYwTPi3B48", title: "Inferno - Canto XIX - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "23:46", id: "4MbscGhd_yw", title: "Bartolomé Bermejo - Trittico della Vergine di Montserrat", tag: "Arte & Simboli" },
],
2: [ // MARTEDÌ - massima variazione di genere
  { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio trasmissioni", tag: "ARS EUROPA TV" },
  { time: "08:02", id: "PeDzAGHnkLw", title: "Decameron - Il frate avido e la brodaglia dei poveri", tag: "Decameron" },
  { time: "08:11", id: "06MijRmCqmQ", title: "Inferno - Canto XX - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "08:23", id: "UU9BLVei6QU", title: "L'occhio di Horus - Antico Egitto - Semeion", tag: "Semeion" },
  { time: "08:37", id: "i4jGjxC-qbE", title: "Giotto - Storie di San Francesco - Parte 1 di 3", tag: "Arte & Simboli" },
  { time: "09:10", id: "1JTtwMU3W4c", title: "Cyrano de Bergerac - Edmond Rostand, Non, merci", tag: "Letteratura" },
  { time: "09:18", id: "nfr3Y1z5dEA", title: "Le Supplici - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "09:41", id: "jNGOdGlE7LQ", title: "La Lupa - I simboli e la storia di Roma", tag: "Mitologia" },
  { time: "09:49", id: "7leFAVmV71Y", title: "Nehusthan - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "09:55", id: "bYT2Ok4r8qI", title: "Catullo - Dammi mille baci - Carme V", tag: "Poesia" },
  { time: "09:59", id: "pqFlJHOibGI", title: "Democrito e gli atomi - Philosophia", tag: "Filosofia" },
  { time: "10:10", id: "2eNrA0pvehA", title: "La sedia - Sign&Design - 1ª puntata", tag: "Design" },
  { time: "10:48", id: "7Y3g-9sAX2g", title: "Il segno del comando nell'Antica Roma", tag: "Storia" },
  { time: "10:56", id: "M3SAVcBKSW4", title: "Marco, il leone del deserto - Tetramorfo", tag: "Tetramorfo" },
  { time: "11:05", id: "bVVeeRVkKAE", title: "Montale e il male di vivere - profeta del nostro presente", tag: "I principi della poesia" },
  { time: "11:35", id: "dyHRAo_bOjA", title: "Né Apocalittici né Integrati - Prima puntata - la terza via dell'Intelligenza Artificiale", tag: "Semiotica Intelligenza Artificiale" },
  { time: "11:53", id: "ukXAsImHyDU", title: "Polisemantica - Il mondo in un segno - 2ª puntata", tag: "Semiotica" },
  { time: "12:03", id: "ElM7rPK06k8", title: "Decameron - Come mandare il diavolo all'inferno - III giornata X novella", tag: "Decameron" },
  { time: "12:14", id: "Ggb06y1dJTA", title: "Inferno - Canto XXI - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "12:27", id: "H4YXia6yz-E", title: "Vita medievale - Semeion - 4ª puntata", tag: "Semeion" },
  { time: "13:02", id: "Zr3BJG9najM", title: "Jacomart Baço - Madonna Virgo Advocata", tag: "Arte & Simboli" },
  { time: "13:12", id: "U5HuJnOl12s", title: "I consigli di Ovidio - il trucco femminile - Ars Amandi", tag: "Letteratura" },
  { time: "13:19", id: "zOEB44h7S5k", title: "Medea - Euripide - Gli Immortali", tag: "Teatro Greco" },
  { time: "13:39", id: "NGY1ZCjtirA", title: "L'egida, la capra Amaltea e la cornucopia - Mitologia", tag: "Mitologia" },
  { time: "13:46", id: "dESyuomRI3E", title: "I profeti di Baal e il doppio olocausto - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "13:56", id: "4lD4LRrAHL8", title: "Cecco Angiolieri - S'i' fosse foco", tag: "Poesia" },
  { time: "14:00", id: "MYEi1LhYlo4", title: "Protagora e le antilogie - Philosophia", tag: "Filosofia" },
  { time: "14:10", id: "q8-VMJW1r80", title: "Il tavolo - Sign&Design - 2ª puntata", tag: "Design" },
  { time: "14:39", id: "_n092qNIw7o", title: "La simbologia dello Scarabeo sacro nell'Antico Egitto", tag: "Storia" },
  { time: "14:51", id: "T6_0Hzog4x0", title: "Luca, lo scriba della mansuetudine - Tetramorfo", tag: "Tetramorfo" },
  { time: "15:04", id: "7PHWv12rfXM", title: "Salvatore Quasimodo - gli elementi della creazione", tag: "I principi della poesia" },
  { time: "15:32", id: "hboGN6-AvYo", title: "Né Apocalittici né Integrati - Seconda puntata - Simnoesi, pensare insieme, oltre lo specchio", tag: "Semiotica Intelligenza Artificiale" },
  { time: "15:47", id: "c4U77oicbuU", title: "Polisemantica - Il mondo in un segno - 3ª puntata", tag: "Semiotica" },
  { time: "15:57", id: "8tkD5HhoxYM", title: "Decameron - Chichibìo e la gru - VI giornata IV novella", tag: "Decameron" },
  { time: "16:06", id: "VauwHvkB68s", title: "Inferno - Canto XXII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "16:19", id: "mwSAxNQ_re0", title: "Società dell'antica Roma - Semeion - 5ª puntata", tag: "Semeion" },
  { time: "16:58", id: "0hpZAYhWJZc", title: "Significati nascosti nell'Allegoria della Prudenza - Tiziano", tag: "Arte & Simboli" },
  { time: "17:10", id: "JIDwzu-phUo", title: "I consigli di Marco Aurelio - la cooperazione", tag: "Letteratura" },
  { time: "17:17", id: "uaSEfOUDRDo", title: "Edipo Re - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "17:38", id: "59mof2mvVaw", title: "Simbologia di Ercole e Anteo - Pollaiolo", tag: "Mitologia" },
  { time: "18:01", id: "_CrCTW4W41A", title: "Susanna e i vecchioni - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "18:12", id: "xGA5AEx0HdQ", title: "Ugo Foscolo - Alla sera", tag: "Poesia" },
  { time: "18:16", id: "msTcwXQM3Qs", title: "Gorgia e la parola - Philosophia", tag: "Filosofia" },
  { time: "18:28", id: "dly0X-1e3bo", title: "Il letto - Sign&Design - 3ª puntata", tag: "Design" },
  { time: "19:02", id: "xLiWCB2m9Jg", title: "I simboli sacerdotali nell'antica Roma", tag: "Storia" },
  { time: "19:13", id: "KIPYOCWYVSU", title: "Giovanni, lo sguardo dell'aquila - Tetramorfo", tag: "Tetramorfo" },
  { time: "19:29", id: "UUSpcCJPgA8", title: "Giuseppe Ungaretti - i punti cardinali dell'ispirazione", tag: "I principi della poesia" },
  { time: "20:42", id: "9jSQdHofi5c", title: "Né Apocalittici né Integrati - Terza puntata - L'Emittente nascosto", tag: "Semiotica Intelligenza Artificiale" },
  { time: "20:59", id: "T9m9cm0dhWY", title: "Decameron - Come attaccare la coda a una cavalla - IX giornata X novella", tag: "Decameron" },
  { time: "21:11", id: "Kd2YKZFkehY", title: "Inferno - Canto XXIII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "21:26", id: "hPWQR2BU49Y", title: "Religioni del Mediterraneo - Semeion - 6ª puntata", tag: "Semeion" },
  { time: "22:00", id: "vrCTJMpuRG8", title: "Simbologia del Paese della Cuccagna - Pieter Brueghel il Vecchio", tag: "Arte & Simboli" },
  { time: "22:16", id: "4JhzDRygmAI", title: "I consigli di Cicerone - il valore dell'amicizia", tag: "Letteratura" },
  { time: "22:23", id: "4O8X48ICIaw", title: "I sette contro Tebe - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "22:47", id: "-kT2WSjxw20", title: "L'ulivo, la civetta e il serpente - I Simboli e la Storia", tag: "Mitologia" },
  { time: "22:55", id: "_RqV9r-Wm74", title: "Lo Spirito Santo nel Cristianesimo - Sacrum", tag: "Sacrum" },
  { time: "23:03", id: "HQqdZ18-UHA", title: "Giacomo Leopardi - L'Infinito", tag: "Poesia" },
  { time: "23:07", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria - I presocratici - Philosophia", tag: "Filosofia" },
  { time: "23:15", id: "LTmiNv4V0FM", title: "La lampada nell'Arte", tag: "Design" },
  { time: "23:27", id: "s6QnfgVPxZA", title: "I simboli dell'alchimia nel Medioevo", tag: "Storia" },
  { time: "23:35", id: "9K_bfj937Pg", title: "Decameron - Un mercante ebreo in Vaticano - I giornata II novella", tag: "Decameron" },
  { time: "23:47", id: "iOnxQXe8MbM", title: "Inferno - Canto XXIV - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
],
3: [ // MERCOLEDÌ - massima variazione di genere, Divina Commedia in ordine crescente
  { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio trasmissioni", tag: "ARS EUROPA TV" },
  { time: "08:02", id: "ElM7rPK06k8", title: "Decameron - Come mandare il diavolo all'inferno - III giornata X novella", tag: "Decameron" },
  { time: "08:13", id: "gywGQZSB8ZE", title: "Inferno - Canto XXV - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "08:26", id: "UU9BLVei6QU", title: "L'occhio di Horus - Antico Egitto - Semeion", tag: "Semeion" },
  { time: "08:40", id: "i4hB8HMOSW8", title: "Giovanni Bellini - Polittico di San Vincenzo Ferrer", tag: "Arte & Simboli" },
  { time: "08:58", id: "1JTtwMU3W4c", title: "Cyrano de Bergerac - Edmond Rostand, Non, merci", tag: "Letteratura" },
  { time: "09:06", id: "zOEB44h7S5k", title: "Medea - Euripide - Gli Immortali", tag: "Teatro Greco" },
  { time: "09:26", id: "jNGOdGlE7LQ", title: "La Lupa - I simboli e la storia di Roma", tag: "Mitologia" },
  { time: "09:34", id: "YDGpLW-lSrc", title: "Madian e i 300 di Gedeone - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "09:49", id: "bYT2Ok4r8qI", title: "Catullo - Dammi mille baci - Carme V", tag: "Poesia" },
  { time: "09:53", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria - I presocratici - Philosophia", tag: "Filosofia" },
  { time: "10:01", id: "2eNrA0pvehA", title: "La sedia - Sign&Design - 1ª puntata", tag: "Design" },
  { time: "10:39", id: "7Y3g-9sAX2g", title: "Il segno del comando nell'Antica Roma", tag: "Storia" },
  { time: "10:47", id: "M3SAVcBKSW4", title: "Marco, il leone del deserto - Tetramorfo", tag: "Tetramorfo" },
  { time: "10:56", id: "bVVeeRVkKAE", title: "Montale e il male di vivere - profeta del nostro presente", tag: "I principi della poesia" },
  { time: "11:26", id: "dyHRAo_bOjA", title: "Né Apocalittici né Integrati - Prima puntata - la terza via dell'Intelligenza Artificiale", tag: "Semiotica Intelligenza Artificiale" },
  { time: "11:44", id: "ukXAsImHyDU", title: "Polisemantica - Il mondo in un segno - 2ª puntata", tag: "Semiotica" },
  { time: "11:54", id: "8tkD5HhoxYM", title: "Decameron - Chichibìo e la gru - VI giornata IV novella", tag: "Decameron" },
  { time: "12:03", id: "JY3EdVzKnVQ", title: "Inferno - Canto XXVI - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "12:17", id: "H4YXia6yz-E", title: "Vita medievale - Semeion - 4ª puntata", tag: "Semeion" },
  { time: "12:52", id: "7ZRo9cVIazE", title: "Simbologia del Giudizio Universale - Luca Signorelli", tag: "Arte & Simboli" },
  { time: "13:11", id: "U5HuJnOl12s", title: "I consigli di Ovidio - il trucco femminile - Ars Amandi", tag: "Letteratura" },
  { time: "13:18", id: "uaSEfOUDRDo", title: "Edipo Re - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "13:39", id: "NGY1ZCjtirA", title: "L'egida, la capra Amaltea e la cornucopia - Mitologia", tag: "Mitologia" },
  { time: "13:46", id: "EUKj2MyULiw", title: "Apocalisse: le ultime parole di Dio", tag: "Sacrum" },
  { time: "14:36", id: "4lD4LRrAHL8", title: "Cecco Angiolieri - S'i' fosse foco", tag: "Poesia" },
  { time: "14:40", id: "1zSwyFPn4Yk", title: "Socrate - Philosophia", tag: "Filosofia" },
  { time: "14:49", id: "q8-VMJW1r80", title: "Il tavolo - Sign&Design - 2ª puntata", tag: "Design" },
  { time: "15:18", id: "_n092qNIw7o", title: "La simbologia dello Scarabeo sacro nell'Antico Egitto", tag: "Storia" },
  { time: "15:30", id: "T6_0Hzog4x0", title: "Luca, lo scriba della mansuetudine - Tetramorfo", tag: "Tetramorfo" },
  { time: "15:43", id: "7PHWv12rfXM", title: "Salvatore Quasimodo - gli elementi della creazione", tag: "I principi della poesia" },
  { time: "16:11", id: "hboGN6-AvYo", title: "Né Apocalittici né Integrati - Seconda puntata - Simnoesi, pensare insieme, oltre lo specchio", tag: "Semiotica Intelligenza Artificiale" },
  { time: "16:26", id: "c4U77oicbuU", title: "Polisemantica - Il mondo in un segno - 3ª puntata", tag: "Semiotica" },
  { time: "16:36", id: "T9m9cm0dhWY", title: "Decameron - Come attaccare la coda a una cavalla - IX giornata X novella", tag: "Decameron" },
  { time: "16:48", id: "pPPa7qJNe8U", title: "Inferno - Canto XXVII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "17:00", id: "mwSAxNQ_re0", title: "Società dell'antica Roma - Semeion - 5ª puntata", tag: "Semeion" },
  { time: "17:39", id: "e5UEQOsR85A", title: "Simbologia della Flagellazione di Cristo - Piero della Francesca", tag: "Arte & Simboli" },
  { time: "18:09", id: "JIDwzu-phUo", title: "I consigli di Marco Aurelio - la cooperazione", tag: "Letteratura" },
  { time: "18:16", id: "4O8X48ICIaw", title: "I sette contro Tebe - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "18:40", id: "59mof2mvVaw", title: "Simbologia di Ercole e Anteo - Pollaiolo", tag: "Mitologia" },
  { time: "19:03", id: "jeHmaJmp3wg", title: "Nehusthan, il serpente di bronzo - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "19:11", id: "xGA5AEx0HdQ", title: "Ugo Foscolo - Alla sera", tag: "Poesia" },
  { time: "19:15", id: "5coSTdhVpuU", title: "Platone - Philosophia", tag: "Filosofia" },
  { time: "19:28", id: "dly0X-1e3bo", title: "Il letto - Sign&Design - 3ª puntata", tag: "Design" },
  { time: "20:02", id: "xLiWCB2m9Jg", title: "I simboli sacerdotali nell'antica Roma", tag: "Storia" },
  { time: "20:13", id: "KIPYOCWYVSU", title: "Giovanni, lo sguardo dell'aquila - Tetramorfo", tag: "Tetramorfo" },
  { time: "20:29", id: "UUSpcCJPgA8", title: "Giuseppe Ungaretti - i punti cardinali dell'ispirazione", tag: "I principi della poesia" },
  { time: "21:42", id: "9jSQdHofi5c", title: "Né Apocalittici né Integrati - Terza puntata - L'Emittente nascosto", tag: "Semiotica Intelligenza Artificiale" },
  { time: "21:59", id: "9K_bfj937Pg", title: "Decameron - Un mercante ebreo in Vaticano - I giornata II novella", tag: "Decameron" },
  { time: "22:11", id: "Eu0bEkB7tiw", title: "Inferno - Canto XXVIII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "22:23", id: "hPWQR2BU49Y", title: "Religioni del Mediterraneo - Semeion - 6ª puntata", tag: "Semeion" },
  { time: "22:57", id: "rZMsiMAEY4s", title: "Simbologia della Morte della Vergine - Caravaggio", tag: "Arte & Simboli" },
  { time: "23:18", id: "4JhzDRygmAI", title: "I consigli di Cicerone - il valore dell'amicizia", tag: "Letteratura" },
  { time: "23:25", id: "9wxNflU3IFQ", title: "I Persiani - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "23:55", id: "-kT2WSjxw20", title: "L'ulivo, la civetta e il serpente - I Simboli e la Storia", tag: "Mitologia" },
],
4: [ // GIOVEDÌ - massima variazione di genere, Divina Commedia in ordine crescente
  { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio trasmissioni", tag: "ARS EUROPA TV" },
  { time: "08:02", id: "ElM7rPK06k8", title: "Decameron - Come mandare il diavolo all'inferno - III giornata X novella", tag: "Decameron" },
  { time: "08:13", id: "BxbUC62hzaE", title: "Inferno - Canto XXIX - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "08:26", id: "UU9BLVei6QU", title: "L'occhio di Horus - Antico Egitto - Semeion", tag: "Semeion" },
  { time: "08:40", id: "bdrOIWKaZ0Y", title: "Pietro Lorenzetti - Beata Umiltà e storie della sua vita", tag: "Arte & Simboli" },
  { time: "08:51", id: "1JTtwMU3W4c", title: "Cyrano de Bergerac - Edmond Rostand, Non, merci", tag: "Letteratura" },
  { time: "08:59", id: "zOEB44h7S5k", title: "Medea - Euripide - Gli Immortali", tag: "Teatro Greco" },
  { time: "09:19", id: "jNGOdGlE7LQ", title: "La Lupa - I simboli e la storia di Roma", tag: "Mitologia" },
  { time: "09:27", id: "YDGpLW-lSrc", title: "Madian e i 300 di Gedeone - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "09:42", id: "bYT2Ok4r8qI", title: "Catullo - Dammi mille baci - Carme V", tag: "Poesia" },
  { time: "09:46", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria - I presocratici - Philosophia", tag: "Filosofia" },
  { time: "09:54", id: "2eNrA0pvehA", title: "La sedia - Sign&Design - 1ª puntata", tag: "Design" },
  { time: "10:32", id: "7Y3g-9sAX2g", title: "Il segno del comando nell'Antica Roma", tag: "Storia" },
  { time: "10:40", id: "M3SAVcBKSW4", title: "Marco, il leone del deserto - Tetramorfo", tag: "Tetramorfo" },
  { time: "10:49", id: "bVVeeRVkKAE", title: "Montale e il male di vivere - profeta del nostro presente", tag: "I principi della poesia" },
  { time: "11:19", id: "dyHRAo_bOjA", title: "Né Apocalittici né Integrati - Prima puntata - la terza via dell'Intelligenza Artificiale", tag: "Semiotica Intelligenza Artificiale" },
  { time: "11:37", id: "ukXAsImHyDU", title: "Polisemantica - Il mondo in un segno - 2ª puntata", tag: "Semiotica" },
  { time: "11:47", id: "8tkD5HhoxYM", title: "Decameron - Chichibìo e la gru - VI giornata IV novella", tag: "Decameron" },
  { time: "11:56", id: "nGdK0Bn9srA", title: "Inferno - Canto XXX - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "12:10", id: "H4YXia6yz-E", title: "Vita medievale - Semeion - 4ª puntata", tag: "Semeion" },
  { time: "12:45", id: "XfFiEQ2preg", title: "Giotto - Storie di San Francesco - Parte 3 di 3", tag: "Arte & Simboli" },
  { time: "13:12", id: "U5HuJnOl12s", title: "I consigli di Ovidio - il trucco femminile - Ars Amandi", tag: "Letteratura" },
  { time: "13:19", id: "uaSEfOUDRDo", title: "Edipo Re - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "13:40", id: "NGY1ZCjtirA", title: "L'egida, la capra Amaltea e la cornucopia - Mitologia", tag: "Mitologia" },
  { time: "13:47", id: "EUKj2MyULiw", title: "Apocalisse: le ultime parole di Dio", tag: "Sacrum" },
  { time: "14:37", id: "4lD4LRrAHL8", title: "Cecco Angiolieri - S'i' fosse foco", tag: "Poesia" },
  { time: "14:41", id: "1zSwyFPn4Yk", title: "Socrate - Philosophia", tag: "Filosofia" },
  { time: "14:50", id: "q8-VMJW1r80", title: "Il tavolo - Sign&Design - 2ª puntata", tag: "Design" },
  { time: "15:19", id: "_n092qNIw7o", title: "La simbologia dello Scarabeo sacro nell'Antico Egitto", tag: "Storia" },
  { time: "15:31", id: "T6_0Hzog4x0", title: "Luca, lo scriba della mansuetudine - Tetramorfo", tag: "Tetramorfo" },
  { time: "15:44", id: "7PHWv12rfXM", title: "Salvatore Quasimodo - gli elementi della creazione", tag: "I principi della poesia" },
  { time: "16:12", id: "hboGN6-AvYo", title: "Né Apocalittici né Integrati - Seconda puntata - Simnoesi, pensare insieme, oltre lo specchio", tag: "Semiotica Intelligenza Artificiale" },
  { time: "16:27", id: "c4U77oicbuU", title: "Polisemantica - Il mondo in un segno - 3ª puntata", tag: "Semiotica" },
  { time: "16:37", id: "T9m9cm0dhWY", title: "Decameron - Come attaccare la coda a una cavalla - IX giornata X novella", tag: "Decameron" },
  { time: "16:49", id: "bMXrHZwHJ7E", title: "Inferno - Canto XXXI - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "17:01", id: "mwSAxNQ_re0", title: "Società dell'antica Roma - Semeion - 5ª puntata", tag: "Semeion" },
  { time: "17:40", id: "yUEMOT8J8KU", title: "Giandomenico Tiepolo - Scena di Carnevale - Il minuetto", tag: "Arte & Simboli" },
  { time: "17:56", id: "JIDwzu-phUo", title: "I consigli di Marco Aurelio - la cooperazione", tag: "Letteratura" },
  { time: "18:03", id: "4O8X48ICIaw", title: "I sette contro Tebe - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "18:27", id: "59mof2mvVaw", title: "Simbologia di Ercole e Anteo - Pollaiolo", tag: "Mitologia" },
  { time: "18:50", id: "jeHmaJmp3wg", title: "Nehusthan, il serpente di bronzo - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "18:58", id: "xGA5AEx0HdQ", title: "Ugo Foscolo - Alla sera", tag: "Poesia" },
  { time: "19:02", id: "5coSTdhVpuU", title: "Platone - Philosophia", tag: "Filosofia" },
  { time: "19:15", id: "dly0X-1e3bo", title: "Il letto - Sign&Design - 3ª puntata", tag: "Design" },
  { time: "19:49", id: "xLiWCB2m9Jg", title: "I simboli sacerdotali nell'antica Roma", tag: "Storia" },
  { time: "20:00", id: "KIPYOCWYVSU", title: "Giovanni, lo sguardo dell'aquila - Tetramorfo", tag: "Tetramorfo" },
  { time: "20:16", id: "UUSpcCJPgA8", title: "Giuseppe Ungaretti - i punti cardinali dell'ispirazione", tag: "I principi della poesia" },
  { time: "21:29", id: "9jSQdHofi5c", title: "Né Apocalittici né Integrati - Terza puntata - L'Emittente nascosto", tag: "Semiotica Intelligenza Artificiale" },
  { time: "21:46", id: "9K_bfj937Pg", title: "Decameron - Un mercante ebreo in Vaticano - I giornata II novella", tag: "Decameron" },
  { time: "21:58", id: "a5z29VNQTyc", title: "Inferno - Canto XXXII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "22:14", id: "hPWQR2BU49Y", title: "Religioni del Mediterraneo - Semeion - 6ª puntata", tag: "Semeion" },
  { time: "22:48", id: "EsbBvV7sU1k", title: "Simbologia di Riposo durante la fuga in Egitto - Caravaggio", tag: "Arte & Simboli" },
  { time: "23:05", id: "4JhzDRygmAI", title: "I consigli di Cicerone - il valore dell'amicizia", tag: "Letteratura" },
  { time: "23:12", id: "9wxNflU3IFQ", title: "I Persiani - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "23:42", id: "-kT2WSjxw20", title: "L'ulivo, la civetta e il serpente - I Simboli e la Storia", tag: "Mitologia" },
  { time: "23:50", id: "_AHY1IOE1Hg", title: "I Demoni - Sacrum, i simboli nelle religioni", tag: "Sacrum" },
],
5: [ // VENERDÌ - massima variazione di genere, Divina Commedia in ordine crescente
  { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio trasmissioni", tag: "ARS EUROPA TV" },
  { time: "08:02", id: "ElM7rPK06k8", title: "Decameron - Come mandare il diavolo all'inferno - III giornata X novella", tag: "Decameron" },
  { time: "08:13", id: "kNR3hnu8mew", title: "Inferno - Canto XXXIII - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "08:28", id: "UU9BLVei6QU", title: "L'occhio di Horus - Antico Egitto - Semeion", tag: "Semeion" },
  { time: "08:42", id: "_rfdWloavPE", title: "Simbologia della Natività con i santi Lorenzo e Francesco - Caravaggio", tag: "Arte & Simboli" },
  { time: "08:58", id: "1JTtwMU3W4c", title: "Cyrano de Bergerac - Edmond Rostand, Non, merci", tag: "Letteratura" },
  { time: "09:06", id: "zOEB44h7S5k", title: "Medea - Euripide - Gli Immortali", tag: "Teatro Greco" },
  { time: "09:26", id: "jNGOdGlE7LQ", title: "La Lupa - I simboli e la storia di Roma", tag: "Mitologia" },
  { time: "09:34", id: "YDGpLW-lSrc", title: "Madian e i 300 di Gedeone - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "09:49", id: "bYT2Ok4r8qI", title: "Catullo - Dammi mille baci - Carme V", tag: "Poesia" },
  { time: "09:53", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria - I presocratici - Philosophia", tag: "Filosofia" },
  { time: "10:01", id: "2eNrA0pvehA", title: "La sedia - Sign&Design - 1ª puntata", tag: "Design" },
  { time: "10:39", id: "7Y3g-9sAX2g", title: "Il segno del comando nell'Antica Roma", tag: "Storia" },
  { time: "10:47", id: "M3SAVcBKSW4", title: "Marco, il leone del deserto - Tetramorfo", tag: "Tetramorfo" },
  { time: "10:56", id: "bVVeeRVkKAE", title: "Montale e il male di vivere - profeta del nostro presente", tag: "I principi della poesia" },
  { time: "11:26", id: "dyHRAo_bOjA", title: "Né Apocalittici né Integrati - Prima puntata - la terza via dell'Intelligenza Artificiale", tag: "Semiotica Intelligenza Artificiale" },
  { time: "11:44", id: "ukXAsImHyDU", title: "Polisemantica - Il mondo in un segno - 2ª puntata", tag: "Semiotica" },
  { time: "11:54", id: "8tkD5HhoxYM", title: "Decameron - Chichibìo e la gru - VI giornata IV novella", tag: "Decameron" },
  { time: "12:03", id: "3vvVMB14ULo", title: "Inferno - Canto XXXIV - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "12:17", id: "H4YXia6yz-E", title: "Vita medievale - Semeion - 4ª puntata", tag: "Semeion" },
  { time: "12:52", id: "Vxbslrddq_c", title: "Maestro Venceslao - Dicembre nel Ciclo dei Mesi di Torre Aquila", tag: "Arte & Simboli" },
  { time: "13:07", id: "U5HuJnOl12s", title: "I consigli di Ovidio - il trucco femminile - Ars Amandi", tag: "Letteratura" },
  { time: "13:14", id: "uaSEfOUDRDo", title: "Edipo Re - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "13:35", id: "NGY1ZCjtirA", title: "L'egida, la capra Amaltea e la cornucopia - Mitologia", tag: "Mitologia" },
  { time: "13:42", id: "EUKj2MyULiw", title: "Apocalisse: le ultime parole di Dio", tag: "Sacrum" },
  { time: "14:32", id: "4lD4LRrAHL8", title: "Cecco Angiolieri - S'i' fosse foco", tag: "Poesia" },
  { time: "14:36", id: "1zSwyFPn4Yk", title: "Socrate - Philosophia", tag: "Filosofia" },
  { time: "14:45", id: "q8-VMJW1r80", title: "Il tavolo - Sign&Design - 2ª puntata", tag: "Design" },
  { time: "15:14", id: "_n092qNIw7o", title: "La simbologia dello Scarabeo sacro nell'Antico Egitto", tag: "Storia" },
  { time: "15:26", id: "T6_0Hzog4x0", title: "Luca, lo scriba della mansuetudine - Tetramorfo", tag: "Tetramorfo" },
  { time: "15:39", id: "7PHWv12rfXM", title: "Salvatore Quasimodo - gli elementi della creazione", tag: "I principi della poesia" },
  { time: "16:07", id: "hboGN6-AvYo", title: "Né Apocalittici né Integrati - Seconda puntata - Simnoesi, pensare insieme, oltre lo specchio", tag: "Semiotica Intelligenza Artificiale" },
  { time: "16:22", id: "c4U77oicbuU", title: "Polisemantica - Il mondo in un segno - 3ª puntata", tag: "Semiotica" },
  { time: "16:32", id: "T9m9cm0dhWY", title: "Decameron - Come attaccare la coda a una cavalla - IX giornata X novella", tag: "Decameron" },
  { time: "16:44", id: "9Xo2rV75CBg", title: "Inferno - Canto I - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "17:02", id: "mwSAxNQ_re0", title: "Società dell'antica Roma - Semeion - 5ª puntata", tag: "Semeion" },
  { time: "17:41", id: "VE1PrYiv1Vw", title: "Simbologia del Seppellimento di Santa Lucia - Caravaggio", tag: "Arte & Simboli" },
  { time: "17:54", id: "JIDwzu-phUo", title: "I consigli di Marco Aurelio - la cooperazione", tag: "Letteratura" },
  { time: "18:01", id: "4O8X48ICIaw", title: "I sette contro Tebe - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "18:25", id: "59mof2mvVaw", title: "Simbologia di Ercole e Anteo - Pollaiolo", tag: "Mitologia" },
  { time: "18:48", id: "jeHmaJmp3wg", title: "Nehusthan, il serpente di bronzo - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "18:56", id: "xGA5AEx0HdQ", title: "Ugo Foscolo - Alla sera", tag: "Poesia" },
  { time: "19:00", id: "5coSTdhVpuU", title: "Platone - Philosophia", tag: "Filosofia" },
  { time: "19:13", id: "dly0X-1e3bo", title: "Il letto - Sign&Design - 3ª puntata", tag: "Design" },
  { time: "19:47", id: "xLiWCB2m9Jg", title: "I simboli sacerdotali nell'antica Roma", tag: "Storia" },
  { time: "19:58", id: "KIPYOCWYVSU", title: "Giovanni, lo sguardo dell'aquila - Tetramorfo", tag: "Tetramorfo" },
  { time: "20:14", id: "UUSpcCJPgA8", title: "Giuseppe Ungaretti - i punti cardinali dell'ispirazione", tag: "I principi della poesia" },
  { time: "21:27", id: "9jSQdHofi5c", title: "Né Apocalittici né Integrati - Terza puntata - L'Emittente nascosto", tag: "Semiotica Intelligenza Artificiale" },
  { time: "21:44", id: "9K_bfj937Pg", title: "Decameron - Un mercante ebreo in Vaticano - I giornata II novella", tag: "Decameron" },
  { time: "21:56", id: "HPgtfRKoH-4", title: "Inferno - Canto II - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "22:10", id: "hPWQR2BU49Y", title: "Religioni del Mediterraneo - Semeion - 6ª puntata", tag: "Semeion" },
  { time: "22:44", id: "FsoXI_2VwNk", title: "Simbologia dell'Adorazione dei Magi - Sandro Botticelli", tag: "Arte & Simboli" },
  { time: "23:05", id: "4JhzDRygmAI", title: "I consigli di Cicerone - il valore dell'amicizia", tag: "Letteratura" },
  { time: "23:12", id: "9wxNflU3IFQ", title: "I Persiani - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "23:42", id: "-kT2WSjxw20", title: "L'ulivo, la civetta e il serpente - I Simboli e la Storia", tag: "Mitologia" },
  { time: "23:50", id: "_AHY1IOE1Hg", title: "I Demoni - Sacrum, i simboli nelle religioni", tag: "Sacrum" },
],
6: [ // SABATO - massima variazione di genere, Divina Commedia in ordine crescente
  { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio trasmissioni", tag: "ARS EUROPA TV" },
  { time: "08:02", id: "ElM7rPK06k8", title: "Decameron - Come mandare il diavolo all'inferno - III giornata X novella", tag: "Decameron" },
  { time: "08:13", id: "9Xo2rV75CBg", title: "Inferno - Canto I - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "08:31", id: "UU9BLVei6QU", title: "L'occhio di Horus - Antico Egitto - Semeion", tag: "Semeion" },
  { time: "08:45", id: "dBcoGyxSSQ0", title: "Donatello - Maddalena penitente", tag: "Arte & Simboli" },
  { time: "08:54", id: "1JTtwMU3W4c", title: "Cyrano de Bergerac - Edmond Rostand, Non, merci", tag: "Letteratura" },
  { time: "09:02", id: "zOEB44h7S5k", title: "Medea - Euripide - Gli Immortali", tag: "Teatro Greco" },
  { time: "09:22", id: "jNGOdGlE7LQ", title: "La Lupa - I simboli e la storia di Roma", tag: "Mitologia" },
  { time: "09:30", id: "YDGpLW-lSrc", title: "Madian e i 300 di Gedeone - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "09:45", id: "bYT2Ok4r8qI", title: "Catullo - Dammi mille baci - Carme V", tag: "Poesia" },
  { time: "09:49", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria - I presocratici - Philosophia", tag: "Filosofia" },
  { time: "09:57", id: "2eNrA0pvehA", title: "La sedia - Sign&Design - 1ª puntata", tag: "Design" },
  { time: "10:35", id: "7Y3g-9sAX2g", title: "Il segno del comando nell'Antica Roma", tag: "Storia" },
  { time: "10:43", id: "M3SAVcBKSW4", title: "Marco, il leone del deserto - Tetramorfo", tag: "Tetramorfo" },
  { time: "10:52", id: "bVVeeRVkKAE", title: "Montale e il male di vivere - profeta del nostro presente", tag: "I principi della poesia" },
  { time: "11:22", id: "dyHRAo_bOjA", title: "Né Apocalittici né Integrati - Prima puntata - la terza via dell'Intelligenza Artificiale", tag: "Semiotica Intelligenza Artificiale" },
  { time: "11:40", id: "ukXAsImHyDU", title: "Polisemantica - Il mondo in un segno - 2ª puntata", tag: "Semiotica" },
  { time: "11:50", id: "8tkD5HhoxYM", title: "Decameron - Chichibìo e la gru - VI giornata IV novella", tag: "Decameron" },
  { time: "11:59", id: "HPgtfRKoH-4", title: "Inferno - Canto II - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "12:13", id: "H4YXia6yz-E", title: "Vita medievale - Semeion - 4ª puntata", tag: "Semeion" },
  { time: "12:48", id: "mNbR-hfE2gc", title: "Bronzino - Ritratto di Eleonora di Toledo", tag: "Arte & Simboli" },
  { time: "13:01", id: "U5HuJnOl12s", title: "I consigli di Ovidio - il trucco femminile - Ars Amandi", tag: "Letteratura" },
  { time: "13:08", id: "uaSEfOUDRDo", title: "Edipo Re - Sofocle - Gli Immortali", tag: "Teatro Greco" },
  { time: "13:29", id: "NGY1ZCjtirA", title: "L'egida, la capra Amaltea e la cornucopia - Mitologia", tag: "Mitologia" },
  { time: "13:36", id: "EUKj2MyULiw", title: "Apocalisse: le ultime parole di Dio", tag: "Sacrum" },
  { time: "14:26", id: "4lD4LRrAHL8", title: "Cecco Angiolieri - S'i' fosse foco", tag: "Poesia" },
  { time: "14:30", id: "1zSwyFPn4Yk", title: "Socrate - Philosophia", tag: "Filosofia" },
  { time: "14:39", id: "q8-VMJW1r80", title: "Il tavolo - Sign&Design - 2ª puntata", tag: "Design" },
  { time: "15:08", id: "_n092qNIw7o", title: "La simbologia dello Scarabeo sacro nell'Antico Egitto", tag: "Storia" },
  { time: "15:20", id: "T6_0Hzog4x0", title: "Luca, lo scriba della mansuetudine - Tetramorfo", tag: "Tetramorfo" },
  { time: "15:33", id: "7PHWv12rfXM", title: "Salvatore Quasimodo - gli elementi della creazione", tag: "I principi della poesia" },
  { time: "16:01", id: "hboGN6-AvYo", title: "Né Apocalittici né Integrati - Seconda puntata - Simnoesi, pensare insieme, oltre lo specchio", tag: "Semiotica Intelligenza Artificiale" },
  { time: "16:16", id: "c4U77oicbuU", title: "Polisemantica - Il mondo in un segno - 3ª puntata", tag: "Semiotica" },
  { time: "16:26", id: "T9m9cm0dhWY", title: "Decameron - Come attaccare la coda a una cavalla - IX giornata X novella", tag: "Decameron" },
  { time: "16:38", id: "e82uw4hDYME", title: "Inferno - Canto III - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "16:53", id: "S409sg6u1_M", title: "Pirandello: una, nessuna, centomila maschere", tag: "I principi della poesia" },
  { time: "17:32", id: "mVOIPZpLdDk", title: "Sandro Botticelli - Madonna col Bambino e due angeli", tag: "Arte & Simboli" },
  { time: "17:46", id: "JIDwzu-phUo", title: "I consigli di Marco Aurelio - la cooperazione", tag: "Letteratura" },
  { time: "17:53", id: "4O8X48ICIaw", title: "I sette contro Tebe - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "18:17", id: "59mof2mvVaw", title: "Simbologia di Ercole e Anteo - Pollaiolo", tag: "Mitologia" },
  { time: "18:40", id: "jeHmaJmp3wg", title: "Nehusthan, il serpente di bronzo - Storie dalla Bibbia", tag: "Sacrum" },
  { time: "18:48", id: "xGA5AEx0HdQ", title: "Ugo Foscolo - Alla sera", tag: "Poesia" },
  { time: "18:52", id: "5coSTdhVpuU", title: "Platone - Philosophia", tag: "Filosofia" },
  { time: "19:05", id: "dly0X-1e3bo", title: "Il letto - Sign&Design - 3ª puntata", tag: "Design" },
  { time: "19:39", id: "xLiWCB2m9Jg", title: "I simboli sacerdotali nell'antica Roma", tag: "Storia" },
  { time: "19:50", id: "KIPYOCWYVSU", title: "Giovanni, lo sguardo dell'aquila - Tetramorfo", tag: "Tetramorfo" },
  { time: "20:06", id: "UUSpcCJPgA8", title: "Giuseppe Ungaretti - i punti cardinali dell'ispirazione", tag: "I principi della poesia" },
  { time: "21:19", id: "9jSQdHofi5c", title: "Né Apocalittici né Integrati - Terza puntata - L'Emittente nascosto", tag: "Semiotica Intelligenza Artificiale" },
  { time: "21:36", id: "9K_bfj937Pg", title: "Decameron - Un mercante ebreo in Vaticano - I giornata II novella", tag: "Decameron" },
  { time: "21:48", id: "og66tX93Mdg", title: "Inferno - Canto IV - La Divina Commedia per i ragazzi", tag: "Divina Commedia" },
  { time: "22:03", id: "hPWQR2BU49Y", title: "Religioni del Mediterraneo - Semeion - 6ª puntata", tag: "Semeion" },
  { time: "22:37", id: "izDm-2nCABM", title: "Significati nascosti nella Madonna del Cardellino - Raffaello", tag: "Arte & Simboli" },
  { time: "22:52", id: "4JhzDRygmAI", title: "I consigli di Cicerone - il valore dell'amicizia", tag: "Letteratura" },
  { time: "22:59", id: "9wxNflU3IFQ", title: "I Persiani - Eschilo - Gli Immortali", tag: "Teatro Greco" },
  { time: "23:29", id: "-kT2WSjxw20", title: "L'ulivo, la civetta e il serpente - I Simboli e la Storia", tag: "Mitologia" },
  { time: "23:37", id: "_AHY1IOE1Hg", title: "I Demoni - Sacrum, i simboli nelle religioni", tag: "Sacrum" },
],
 };

