// Palinsesto settimanale ARS EUROPA TV
// Catalogo intero, Simboli nell'arte molto frequente
const schedules = {
  0: [ // DOMENICA
    { time: "07:58", id: "nRrWSTaabeQ", title: 'Inizio delle trasmissioni', tag: 'ARS EUROPA TV' },
    { time: "08:00", id: "YDGpLW-lSrc", title: 'MADIAN e i 300 di Gedeone', tag: 'Storie dalla Bibbia' },
    { time: "08:15", id: "pVOr0QbCOZA", title: 'CATERINA, la forza della Sapienza', tag: 'Historica' },
    { time: "08:31", id: "_rfdWloavPE", title: 'Simbologia della Natività con i santi Lorenzo e Francesco - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "08:47", id: "Vjes7xPZgo0", title: 'Calandrino incinto', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "09:01", id: "33LYXRz6E5s", title: 'Adone', tag: 'Simboli, miti e leggende' },
    { time: "09:11", id: "FyOCxDBzYIE", title: 'Simbologia delle sette Virtù - Pollaiolo e Botticelli', tag: 'Simboli nell\'arte' },
    { time: "09:45", id: "CKjDj0O-D4o", title: 'ANTONIO, Abbà - L\'eremita che inventò il monachesimo', tag: 'Historica' },
    { time: "10:03", id: "vGut7h5Wlwc", title: 'Orazio - Carpe Diem, afferra l\'attimo', tag: 'Poesia' },
    { time: "10:06", id: "wqWQ8vjyHPc", title: 'Settembre negli Arazzi Trivulzio - Bramantino e Manifattura di Vigevano', tag: 'Simboli nell\'arte' },
    { time: "10:24", id: "S409sg6u1_M", title: 'PIRANDELLO: una, nessuna, centomila maschere. E la tua qual è?', tag: 'I principi della poesia' },
    { time: "11:04", id: "BqmMSIiR290", title: 'Allegoria del Buon Governo - Ambrogio Lorenzetti', tag: 'Simboli nell\'arte' },
    { time: "11:21", id: "lBnP772e7AA", title: 'I consigli di PLATONE - le buone discussioni', tag: 'Cultura classica' },
    { time: "11:26", id: "bSIeXu1fmZw", title: 'Simbologia dell\'abbigliamento maschile nell\'antica Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "11:36", id: "-4ahGMWqfM8", title: 'Simbologia de La zattera della Medusa - Théodore Géricault', tag: 'Simboli nell\'arte' },
    { time: "11:48", id: "_noxbELcGdc", title: 'Il Pantheon', tag: 'I luoghi, simboli e Storia' },
    { time: "11:57", id: "JxHiv1EbEXY", title: 'Aiace - Sofocle', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "12:40", id: "D4pA1Bs3A_0", title: 'I simboli nell\'Arte - Età Moderna e Contemporanea', tag: 'Simboli nell\'arte' },
    { time: "13:13", id: "Gqmjecp3NTo", title: 'La lampada e la Storia', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "13:24", id: "WqOrir0fsxA", title: 'Simboli e significati nascosti nelle Storie degli ultimi giorni - Luca Signorelli', tag: 'Simboli nell\'arte' },
    { time: "14:09", id: "5DtPo9q0YJo", title: 'VALENTINO, un amore trascendente', tag: 'Historica' },
    { time: "14:22", id: "TvY6zNfDhqo", title: 'Debora e l\'incontro di Sisara e Giaele', tag: 'Storie dalla Bibbia' },
    { time: "14:30", id: "xqulRBS-iIk", title: 'Simbologia di GOLCONDA -  René Magritte', tag: 'Simboli nell\'arte' },
    { time: "14:39", id: "dly0X-1e3bo", title: 'Il letto', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "15:13", id: "BpfNVrGJreE", title: 'Prometeo Incatenato - Eschilo', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "15:38", id: "kcUQ4Mky_3w", title: 'Significati nascosti nella Scuola di Atene - Raffaello', tag: 'Simboli nell\'arte' },
    { time: "15:49", id: "4JhzDRygmAI", title: 'I consigli di CICERONE - il valore dell\'amicizia - De Amicitia', tag: 'Cultura classica' },
    { time: "15:56", id: "EVNS93JNpUM", title: 'I simboli nei mosaici romani', tag: 'Semeion - i simboli e la Storia' },
    { time: "16:04", id: "WSwrZf896pY", title: 'Giotto - Santo Stefano - Museo Horne - Firenze', tag: 'Simboli nell\'arte' },
    { time: "16:22", id: "E3bNrJqqvjQ", title: 'Amuleti e talismani nell\'antica Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "16:32", id: "zzbcMM2Bm8k", title: 'Significati nascosti nel Parnaso - Andrea Mantegna', tag: 'Simboli nell\'arte' },
    { time: "16:59", id: "vGzv0sGe6F8", title: 'Carlo Borromeo - Lo splendore dell\'Umiltà', tag: 'Historica' },
    { time: "17:24", id: "j-QqaWgK3rA", title: 'I consigli di Marco Aurelio - Il giusto atteggiamento - Meditazioni', tag: 'Cultura classica' },
    { time: "17:30", id: "5iUS5P8Yl90", title: 'Carlo Crivelli - Annunciazione di Ascoli', tag: 'Simboli nell\'arte' },
    { time: "17:38", id: "OIbMcxEIubc", title: 'Giovanni di Paolo - Madonna col Bambino e Santi - Creazione e Cacciata dal Paradiso Terrestre', tag: 'Capolavori' },
    { time: "17:52", id: "HQqdZ18-UHA", title: 'Giacomo Leopardi - L\'Infinito', tag: 'Poesia' },
    { time: "17:55", id: "WWy3GpSwbk0", title: 'Simbologia del Martirio di San Matteo - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "18:28", id: "NLPkp1cnsYE", title: 'AMBROGIO, immortale', tag: 'Historica' },
    { time: "19:13", id: "K1F565ijk4E", title: 'Simbologia di Pallade e il centauro -  Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "19:26", id: "U5HuJnOl12s", title: 'I consigli di OVIDIO - il trucco femminile - ARS AMANDI', tag: 'Cultura classica' },
    { time: "19:33", id: "LBdvcDAlFjM", title: 'Filottete  - Sofocle', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "20:05", id: "rZMsiMAEY4s", title: 'Simbologia della Morte della Vergine - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "20:27", id: "bVVeeRVkKAE", title: 'Montale e il male di vivere - la profezia del vuoto moderno', tag: 'I principi della poesia' },
    { time: "20:58", id: "8RHc0dwAVmE", title: 'Orfeo', tag: 'Simboli, miti e leggende' },
    { time: "21:15", id: "ovCXfsiS8EI", title: 'Simbologia di San Giorgio e la Principessa - Pisanello', tag: 'Simboli nell\'arte' },
    { time: "21:27", id: "Bik77BxkBfM", title: 'Beato Angelico - Giudizio Universale', tag: 'Capolavori' },
    { time: "21:40", id: "TjVYh3Jm270", title: 'Simbologia della Dama con l\'ermellino - Leonardo da Vinci', tag: 'Simboli nell\'arte' },
    { time: "21:50", id: "eSQcTSW5u50", title: 'ALCESTI -  Euripide', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "22:21", id: "_RqV9r-Wm74", title: 'Lo Spirito Santo nel Cristianesimo', tag: 'Sacrum' },
    { time: "22:31", id: "kL2UrUxrfWY", title: 'Maestro Olandese o della Germania Settentrionale - Trittico di Gerusalemme', tag: 'Simboli nell\'arte' },
    { time: "22:40", id: "uaSEfOUDRDo", title: 'Edipo re - Sofocle', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "23:01", id: "HkBxKcbf3hE", title: 'TOBIOLO E L\'ANGELO', tag: 'Storie dalla Bibbia' },
  ],
  1: [ // LUNEDI
    { time: "07:58", id: "nRrWSTaabeQ", title: 'Inizio delle trasmissioni', tag: 'ARS EUROPA TV' },
    { time: "08:00", id: "8f5m0M3rmIA", title: 'Giotto - Storie di San Francesco - Assisi', tag: 'Simboli nell\'arte' },
    { time: "09:10", id: "YEmpT3udO4U", title: 'I consigli di Seneca - la virtù - Lettere a Lucilio', tag: 'Cultura classica' },
    { time: "09:14", id: "JgZfs2eImmg", title: 'Vittore Crivelli - Polittico di San Severino', tag: 'Capolavori' },
    { time: "09:23", id: "GAMo-3Ho2e8", title: 'Significati nascosti nei simboli dell\'Anastasi - San Salvatore in Chora', tag: 'Simboli nell\'arte' },
    { time: "09:35", id: "zrSkcpDgWuw", title: 'La Cattedrale di Notre-Dame di Parigi', tag: 'I luoghi, simboli e Storia' },
    { time: "09:48", id: "Fu4cUOiZsa4", title: 'Significato dell\'incontro tra Salomone e la Regina di Saba - Piero della Francesca', tag: 'Simboli nell\'arte' },
    { time: "10:02", id: "4O8X48ICIaw", title: 'I sette contro Tebe - Eschilo', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "10:25", id: "hEbi1jjkfak", title: 'Oftalmoi - Il simbolo dell\'occhio nell\'Antica Grecia', tag: 'Semeion - i simboli e la Storia' },
    { time: "10:33", id: "g6kgO00YunM", title: 'Simbologia della Cena in Emmaus - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "10:53", id: "bimuhQ5N6Wg", title: 'Margarito d’Arezzo - Madonna col Bambino in Trono', tag: 'Capolavori' },
    { time: "11:08", id: "_CrCTW4W41A", title: 'SUSANNA e i vecchioni', tag: 'Storie dalla Bibbia' },
    { time: "11:21", id: "g62lmmoDofI", title: 'Carlo Crivelli - Immacolata Concezione', tag: 'Simboli nell\'arte' },
    { time: "11:39", id: "i4hB8HMOSW8", title: 'Giovanni Bellini - Polittico di San Vincenzo Ferrer', tag: 'Capolavori' },
    { time: "11:57", id: "AUwhHd-t-iw", title: 'Simbologia nella Lotta tra Carnevale e Quaresima -  Pieter Brueghel il Vecchio', tag: 'Simboli nell\'arte' },
    { time: "12:11", id: "8tkD5HhoxYM", title: 'Chichibìo e la gru', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "12:20", id: "gawFAzVeAto", title: 'i consigli di Seneca - la Filosofia', tag: 'Cultura classica' },
    { time: "12:27", id: "mZHs1pTuSjU", title: 'Simbologia dell\'Annunciazione - Leonardo da Vinci', tag: 'Simboli nell\'arte' },
    { time: "12:38", id: "XwVY9Wy6HaI", title: 'I consigli di Seneca - il vero bene - LETTERE A LUCILIO', tag: 'Cultura classica' },
    { time: "12:43", id: "dHmkQOcHcrY", title: 'Il Colosseo', tag: 'I luoghi, simboli e Storia' },
    { time: "12:57", id: "NH8I7DznhYE", title: 'Simbologia de L\'isola dei morti di Arnold Böcklin', tag: 'Simboli nell\'arte' },
    { time: "13:07", id: "J47HGIAt7H0", title: 'GIOSUE\' FERMA IL SOLE', tag: 'Storie dalla Bibbia' },
    { time: "13:15", id: "mcTve-LcWxg", title: 'Simbologia de "Le storie di Maria alla Cappella Scrovegni" -   Giotto', tag: 'Simboli nell\'arte' },
    { time: "13:37", id: "UUSpcCJPgA8", title: 'I PUNTI CARDINALI DELL\'ISPIRAZIONE  -  Giuseppe Ungaretti -  I principi della poesia', tag: 'I principi della poesia' },
    { time: "14:50", id: "pqFlJHOibGI", title: 'Democrito e gli atomi', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "15:01", id: "Vz6OIYM_fKk", title: 'Significato del Ritrovamento e Verifica della Croce - Piero della Francesca', tag: 'Simboli nell\'arte' },
    { time: "15:11", id: "1zXxvYDhG4o", title: 'Psiche', tag: 'Simboli, miti e leggende' },
    { time: "15:29", id: "tgaxKfngNCY", title: 'Alessandro Manzoni - Sentir e meditar', tag: 'Poesia' },
    { time: "15:31", id: "KluoKrQ9lUE", title: 'LA CALUNNIA di Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "15:39", id: "GrqPGuz1N-A", title: 'Antigone - Sofocle', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "16:09", id: "7PHWv12rfXM", title: 'SALVATORE QUASIMODO - Gli elementi della creazione -  I principi della Poesia', tag: 'I principi della poesia' },
    { time: "16:38", id: "DMJU2D2BxOg", title: 'Simbologia dell\'Annunciata di Palermo - Antonello da Messina', tag: 'Simboli nell\'arte' },
    { time: "16:52", id: "86HxQMkRBfo", title: 'Le festività nell\'antica Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "17:05", id: "UlL3gs7cSho", title: 'I mosaici medievali e gli affreschi ottoniani della Cattedrale di Aosta', tag: 'Simboli nell\'arte' },
    { time: "17:14", id: "jJpr7Ttffks", title: 'Dante Alighieri - Tra terra e cielo - I principi della poesia', tag: 'I principi della poesia' },
    { time: "17:52", id: "odGTmKeuCMQ", title: 'Cimabue - Maestà di Assisi', tag: 'Capolavori' },
    { time: "18:04", id: "FQPe1qoCQI8", title: 'Simbologia dei Profeti alla Cappella Sistina - Michelangelo', tag: 'Simboli nell\'arte' },
    { time: "18:44", id: "xKRU6UqRLTQ", title: 'Le Eumenidi - Eschilo', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "19:03", id: "7Y3g-9sAX2g", title: 'Il segno del comando nell\'Antica Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "19:11", id: "ITdd3pc_Yu0", title: 'Simbologia di GUERNICA  -  Pablo Picasso', tag: 'Simboli nell\'arte' },
    { time: "19:19", id: "3-Rc374qiAA", title: 'Il matrimonio romano', tag: 'Semeion - i simboli e la Storia' },
    { time: "19:31", id: "rqf8m8WaTLM", title: 'Simbologia di San Matteo e l\'angelo - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "19:54", id: "1JTtwMU3W4c", title: 'Cyrano de Bergerac - Edmond Rostand, Non, merci - No, grazie', tag: 'Poesia' },
    { time: "19:59", id: "vtJGNqiVUho", title: 'IPPOLITO - Euripide', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "20:51", id: "PbHxVDjfYW4", title: 'Significati nascosti nella Allegoria Sacra - Giovanni Bellini', tag: 'Simboli nell\'arte' },
    { time: "21:06", id: "wStQPVyWzuM", title: 'Ser Ciappelletto', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "21:24", id: "_YN4KrZiSjM", title: 'Le Trachinie - Sofocle', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "21:52", id: "91IGWNwcUAU", title: 'Simbologia della Deposizione - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "22:10", id: "zOEB44h7S5k", title: 'Medea - Euripide', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "22:30", id: "8ARgrY1P1aA", title: 'Simbologia del Paradiso di Giovanni di Paolo', tag: 'Simboli nell\'arte' },
    { time: "22:42", id: "EUKj2MyULiw", title: 'Apocalisse: le ultime parole di Dio', tag: 'Sacrum' },
    { time: "23:32", id: "h2SSOHy_LQg", title: 'Erminio Avarizia', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "23:40", id: "VE1PrYiv1Vw", title: 'Simbologia del Seppellimento di Santa Lucia  - Caravaggio', tag: 'Simboli nell\'arte' },
  ],
  2: [ // MARTEDI
    { time: "07:58", id: "nRrWSTaabeQ", title: 'Inizio delle trasmissioni', tag: 'ARS EUROPA TV' },
    { time: "08:00", id: "5BJaK2Nv3L0", title: 'Empedocle e i quattro elementi', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "08:11", id: "jeHmaJmp3wg", title: 'Nehusthan, il serpente di bronzo', tag: 'Storie dalla Bibbia' },
    { time: "08:19", id: "ZULKBoQ6-l8", title: 'Significati nascosti nell\'Adorazione dei pastori - Andrea Mantegna', tag: 'Simboli nell\'arte' },
    { time: "08:37", id: "_AHY1IOE1Hg", title: 'I Demoni', tag: 'Sacrum' },
    { time: "09:07", id: "dESyuomRI3E", title: 'I profeti di BAAL e il doppio olocausto', tag: 'Storie dalla Bibbia' },
    { time: "09:18", id: "FsoXI_2VwNk", title: 'Simbologia dell\'Adorazione dei Magi - Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "09:38", id: "-SNEvPO-2D4", title: 'Il mobile e la sua simbologia', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "09:48", id: "JURq_FKWOR8", title: 'Significato delle Storie della Vera Croce - Piero della Francesca', tag: 'Simboli nell\'arte' },
    { time: "11:15", id: "xGA5AEx0HdQ", title: 'Ugo Foscolo - Alla sera', tag: 'Poesia' },
    { time: "11:18", id: "MAx6zDUILbQ", title: 'Zenone e i suoi paradossi', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "11:31", id: "Z2ibq-HfwiI", title: 'I simboli di Raffaello - Viaggio nei significati alle Scuderie del Quirinale', tag: 'Simboli nell\'arte' },
    { time: "12:26", id: "Q0NFO2Cs93U", title: 'Anassimene e l\'aria', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "12:34", id: "VzG3biTZ1rg", title: 'Agamennone  -  Eschilo', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "12:52", id: "BuQyh3umWG0", title: 'Simbologia de IL CAMBIAVALUTE CON SUA MOGLIE - Quentin Metsys', tag: 'Simboli nell\'arte' },
    { time: "12:58", id: "0UOJdSzhFrI", title: 'Teti', tag: 'Simboli, miti e leggende' },
    { time: "13:18", id: "AcN6C3L5QKc", title: 'Significato del Sogno di Costantino - Piero della Francesca', tag: 'Simboli nell\'arte' },
    { time: "13:28", id: "gvBOqwT-iJ0", title: 'Ifigenia in Aulide - Euripide', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "14:14", id: "yUEMOT8J8KU", title: 'Giandomenico Tiepolo - Scena di Carnevale [Il minuetto]', tag: 'Capolavori' },
    { time: "14:30", id: "hIJjgqUb-8I", title: 'Simbologia del TONDO DONI  - Michelangelo', tag: 'Simboli nell\'arte' },
    { time: "14:45", id: "9BETjtp1mbA", title: 'Parmenide e l\'Essere', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "14:55", id: "SxTPMNST8Q4", title: 'Le Supplici - Eschilo', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "15:20", id: "Cn_F70P-77o", title: 'Simbologia del Trittico delle Tentazioni di sant\'Antonio di Hieronymus Bosch', tag: 'Simboli nell\'arte' },
    { time: "15:56", id: "PeDzAGHnkLw", title: 'Il frate avido e la brodaglia dei poveri', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "16:05", id: "XiZdP043an0", title: 'Simbologia de LE STORIE DI CRISTO -  GIOTTO', tag: 'Simboli nell\'arte' },
    { time: "17:10", id: "Mz-gYg4bV0Y", title: 'Duccio di Buoninsegna - Madonna con il Bambino e sei angeli', tag: 'Capolavori' },
    { time: "17:23", id: "Ukb7enwrhmU", title: 'Martellino e il finto miracolo', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "17:36", id: "8K6AO9ISUgc", title: 'Allegoria del Cattivo Governo - Ambrogio Lorenzetti', tag: 'Simboli nell\'arte' },
    { time: "17:49", id: "hU_Bq30AsNM", title: 'Europa', tag: 'Simboli, miti e leggende' },
    { time: "18:00", id: "abUpEQBf1b0", title: 'MENE,TEKEL,PERES - la mano fantasma', tag: 'Storie dalla Bibbia' },
    { time: "18:10", id: "gJQIVbPVYx8", title: 'Simbologia dell\'Ultima Cena - Leonardo da Vinci', tag: 'Simboli nell\'arte' },
    { time: "18:59", id: "a_sJka5SgjI", title: 'Il dono di re SALOMONE', tag: 'Storie dalla Bibbia' },
    { time: "19:07", id: "bYT2Ok4r8qI", title: 'Catullo - dammi mille baci - carme V', tag: 'Poesia' },
    { time: "19:10", id: "3aUGhajRXBA", title: 'Simbologia della Messa di Bolsena - Raffaello', tag: 'Simboli nell\'arte' },
    { time: "19:31", id: "0Q3UHX75roM", title: 'I consigli di AGOSTINO - la felicità - le Confessioni', tag: 'Cultura classica' },
    { time: "19:37", id: "-76Y7rX1q3U", title: 'Significati nascosti in Bacco - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "19:54", id: "4lD4LRrAHL8", title: 'Cecco Angiolieri - s\'i\' fosse foco', tag: 'Poesia' },
    { time: "19:57", id: "VNx-F7naSK0", title: 'ELETTRA -  Sofocle', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "20:35", id: "RX2dqu6DE0A", title: 'Andrea Mantegna - Trionfo della Virtù', tag: 'Simboli nell\'arte' },
    { time: "20:41", id: "_5mO9eF7OzA", title: 'IFIGENIA IN TAURIDE - Euripide', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "21:24", id: "q8-VMJW1r80", title: 'Il tavolo', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "21:54", id: "kQPcP2Wcub8", title: 'I Simboli nell\'Arte - Dal Quattrocento al Manierismo', tag: 'Simboli nell\'arte' },
    { time: "22:30", id: "jid79a7Vzf0", title: 'La simbologia delle insegne degli imperatori romani -  Antica Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "22:43", id: "51YNGE-oh3Q", title: 'Simbologia della Madonna del Libro - Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "23:03", id: "Pkmfnn3KcWM", title: 'Talete e l\'acqua', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "23:12", id: "-HHg7SoG04I", title: 'Hugo van der Goes - Trittico Portinari', tag: 'Capolavori' },
    { time: "23:45", id: "fqiHHH72OMs", title: 'Simbologia di Madonna di Santa Trinita - Cimabue', tag: 'Simboli nell\'arte' },
  ],
  3: [ // MERCOLEDI
    { time: "07:58", id: "nRrWSTaabeQ", title: 'Inizio delle trasmissioni', tag: 'ARS EUROPA TV' },
    { time: "08:00", id: "YguWYzvu7Jk", title: 'Giuffredi, il figlio della Capriola', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "08:20", id: "YT6KLLfPhSQ", title: 'Louis Janmot - Il Poema dell\'Anima', tag: 'Capolavori' },
    { time: "08:32", id: "51ko0maD8pY", title: 'Simbologia delle "Très Riches Heures du Duc de Berry" -  FRATELLI LIMBOURG', tag: 'Simboli nell\'arte' },
    { time: "09:13", id: "TNlYUDPzZtg", title: 'ANDROMACA - Euripide', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "10:03", id: "LMjIeNUiopg", title: 'Significato della Morte di Adamo - Piero della Francesca', tag: 'Simboli nell\'arte' },
    { time: "10:17", id: "5coSTdhVpuU", title: 'Platone', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "10:30", id: "gYZlbiG0Mk4", title: 'Edipo a Colono - Sofocle', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "11:19", id: "wO56CDW3m-g", title: 'Simbologia de La liberazione di san Pietro - Raffaello', tag: 'Simboli nell\'arte' },
    { time: "11:31", id: "BLDB2zuKUhA", title: 'ELISEO, la vedova e l\'olio', tag: 'Storie dalla Bibbia' },
    { time: "11:38", id: "msTcwXQM3Qs", title: 'GORGIA e la parola', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "11:51", id: "UolYSLet7rc", title: 'Significato del Cristo morto - Andrea Mantegna', tag: 'Simboli nell\'arte' },
    { time: "12:07", id: "JlDzVj7QrZM", title: 'SAMUELE e la voce misteriosa', tag: 'Storie dalla Bibbia' },
    { time: "12:16", id: "aWlHf7nx3Z8", title: 'San Giuliano, il mercante e la vedovella', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "12:27", id: "q3zuM-qIfn0", title: 'Significati della Nascita di Venere - Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "12:55", id: "VVLf7kk3fo0", title: 'I RACCONTI DI SALLUSTIO - la chiara fama', tag: 'Cultura classica' },
    { time: "13:01", id: "ISGDp4oMwPM", title: 'Simbologia dell\'Incendio di Borgo - Raffaello', tag: 'Simboli nell\'arte' },
    { time: "13:11", id: "7_LUxivWuAM", title: 'LE TROIANE - Euripide', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "14:10", id: "9wxNflU3IFQ", title: 'I Persiani -  Eschilo', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "14:39", id: "nZEBolqQ3KI", title: 'Giotto - Cappella degli Scrovegni - Storie di Anna e Gioacchino', tag: 'Simboli nell\'arte' },
    { time: "15:00", id: "S80kNQbbpNk", title: 'Anassimandro e l\'apeiron', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "15:11", id: "_33jtBhONO0", title: 'Coefore - Eschilo', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "15:28", id: "I9bfxWuUPSY", title: 'Simbologia della Madonna della Seggiola - Raffaello', tag: 'Simboli nell\'arte' },
    { time: "15:47", id: "bC_fklpuU38", title: 'i consigli di Seneca - Tempo ed Equilibrio', tag: 'Cultura classica' },
    { time: "15:56", id: "05RV29HXOI8", title: 'Significati nascosti nello Sposalizio della Vergine - Raffaello', tag: 'Simboli nell\'arte' },
    { time: "16:10", id: "hPWQR2BU49Y", title: 'Religioni del Mediterraneo - Semeion - 6ª puntata', tag: 'Semeion - i simboli e la Storia' },
    { time: "16:45", id: "K1vFnkYUA6c", title: 'I simboli dei sottufficiali romani', tag: 'Semeion - i simboli e la Storia' },
    { time: "16:52", id: "M7C3b1NSM7U", title: 'La classe di danza di Edgar Degas', tag: 'Simboli nell\'arte' },
    { time: "17:03", id: "La8RbJbSL6U", title: 'Pitagora e i numeri', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "17:13", id: "1zSwyFPn4Yk", title: 'Socrate', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "17:22", id: "cNrPGn5qQmY", title: 'Significato della Battaglia di Eraclio e Cosroè - Piero della Francesca', tag: 'Simboli nell\'arte' },
    { time: "17:36", id: "T9m9cm0dhWY", title: 'Come attaccare la coda a una cavalla', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "17:48", id: "XCLbewnTJ9s", title: 'I Coretti e le architetture illusorie di Giotto nell’arco della Cappella degli Scrovegni', tag: 'Simboli nell\'arte' },
    { time: "18:02", id: "EhsO8Dea9yM", title: 'ECUBA - Euripide', tag: 'Gli Immortali - la tragedia greca illustrata' },
    { time: "18:50", id: "gc5RNyVXX-k", title: 'Anathema ad Asclepio - I simboli nell\'antica Grecia', tag: 'Semeion - i simboli e la Storia' },
    { time: "18:57", id: "-g9dPd7B4uA", title: 'Simbologia della Battaglia di Costantino contro Massenzio - Scuola di Raffaello', tag: 'Simboli nell\'arte' },
    { time: "19:11", id: "b0gBKKEZTA8", title: 'L\'usuraio, l\'abate e la fanciulla', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "19:29", id: "oqTUTClIW2I", title: 'Aristotele', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "19:38", id: "M3SAVcBKSW4", title: 'Simbologia della Lippina - Filippo Lippi', tag: 'Simboli nell\'arte' },
    { time: "19:50", id: "SOqN2uepscY", title: 'Eraclito e il fuoco', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "20:02", id: "_n092qNIw7o", title: 'La simbologia dello Scarabeo sacro nell\'Antico Egitto', tag: 'Semeion - i simboli e la Storia' },
    { time: "20:14", id: "2hZy1rsXgj0", title: 'Allegoria delle quattro Stagioni - Bartolomeo Manfredi', tag: 'Simboli nell\'arte' },
    { time: "20:22", id: "3pjCAAs55xo", title: 'I consigli di CICERONE - Le forze nella vecchiaia', tag: 'Cultura classica' },
    { time: "20:30", id: "EvTY-rqb1WY", title: 'Significati dei simboli nella Theotókos di Vladimir', tag: 'Simboli nell\'arte' },
    { time: "20:42", id: "9e4uCJAmljA", title: 'La dama di Guascogna e il re di Cipro', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "20:47", id: "HzIPvLDELVw", title: 'I “signa”, le insegne militari dell\'esercito romano - I Simboli e la Storia - Antica Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "20:54", id: "nIbmYCpuXDo", title: 'Simbologia di Ambasciatori - Hans Holbein il Giovane', tag: 'Simboli nell\'arte' },
    { time: "21:04", id: "uLLIhAn0DJM", title: 'I simboli dei cavalieri medievali - Semeion, i Simboli e la Storia', tag: 'Semeion - i simboli e la Storia' },
    { time: "21:15", id: "KvpEM4bgfZY", title: 'Anassagora e il Nous', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "21:26", id: "AyQIOITtU5c", title: 'Significati nascosti nella Discesa al Limbo - Andrea Mantegna', tag: 'Simboli nell\'arte' },
    { time: "21:39", id: "JBxkizfcJno", title: 'Andreuccio da Perugia e la sorella ritrovata', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "22:03", id: "Jx2XFnoFiHc", title: 'Simbologia della Carità - Pollaiolo - I SIMBOLI NELL\'ARTE', tag: 'Simboli nell\'arte' },
    { time: "22:13", id: "_57OfZukJTs", title: 'Il Sultano Saladino e i tre anelli', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "22:23", id: "redrKZc2HoY", title: 'I simboli dei Pellegrini nel Medioevo', tag: 'Semeion - i simboli e la Storia' },
    { time: "22:31", id: "vrCTJMpuRG8", title: 'Simbologia del Paese della Cuccagna - Pieter Brueghel il Vecchio', tag: 'Simboli nell\'arte' },
    { time: "22:47", id: "5D0qcufRzOw", title: 'Bergamino e l\'avarizia di Cangrande', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "23:00", id: "WgNzIFn9CU4", title: 'I RACCONTI DI PLUTARCO - la fine di Romolo', tag: 'Cultura classica' },
    { time: "23:05", id: "e5UEQOsR85A", title: 'Simbologia della Flagellazione di Cristo - Piero della Francesca', tag: 'Simboli nell\'arte' },
  ],
  4: [ // GIOVEDI
    { time: "07:58", id: "nRrWSTaabeQ", title: 'Inizio delle trasmissioni', tag: 'ARS EUROPA TV' },
    { time: "08:00", id: "NWa0lsE9GlE", title: 'Simbologia di Agosto a Palazzo Schifanoia', tag: 'Capolavori' },
    { time: "08:30", id: "EsbBvV7sU1k", title: 'Simbologia di Riposo durante la fuga in Egitto - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "08:46", id: "9K_bfj937Pg", title: 'Un mercante ebreo in Vaticano', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "08:58", id: "jtStIm5z7II", title: 'I consigli di Seneca - Amicizia', tag: 'Cultura classica' },
    { time: "09:05", id: "mNenPBAaVvI", title: 'Effetti del Buon Governo in città e in campagna - Ambrogio Lorenzetti', tag: 'Simboli nell\'arte' },
    { time: "09:16", id: "QcN8IL5cGiI", title: 'Crisippo', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "09:28", id: "tmyoBjeOX_g", title: 'Misteri dell\'antica Grecia - Semeion - 3ª puntata', tag: 'Semeion - i simboli e la Storia' },
    { time: "09:59", id: "nfr3Y1z5dEA", title: 'Significato dei simboli nella Trasfigurazione - Raffaello', tag: 'Simboli nell\'arte' },
    { time: "10:22", id: "VlLgbobv-Ec", title: 'Claude Monet - Il mare agitato a Étretat', tag: 'Capolavori' },
    { time: "10:27", id: "MYEi1LhYlo4", title: 'PROTAGORA e le antilogie', tag: 'Philosophia - gli amanti della sapienza' },
    { time: "10:39", id: "59mof2mvVaw", title: 'Significati nascosti dell\'Annunciazione di Recanati - Lorenzo Lotto', tag: 'Simboli nell\'arte' },
    { time: "11:02", id: "eX13aqoGOqU", title: 'Il mito dei Fenici - Semeion - 7ª puntata', tag: 'Semeion - i simboli e la Storia' },
    { time: "11:38", id: "SMVLYC94iXY", title: 'I SETTE PECCATI CAPITALI DI HIERONYMUS BOSCH', tag: 'Simboli nell\'arte' },
    { time: "12:02", id: "LlnGoSaqA7Y", title: 'Piero della Francesca - Pala di Montefeltro', tag: 'Capolavori' },
    { time: "12:09", id: "ibNmDm7n1aQ", title: 'I RACCONTI DI SALLUSTIO - la forza del corpo e il vigore dell\'animo - la congiura di Catilina', tag: 'Cultura classica' },
    { time: "12:15", id: "izDm-2nCABM", title: 'Simbologia della Natività mistica - Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "12:31", id: "AxePQgHrhC8", title: 'I consigli di Marco Aurelio - La percezione', tag: 'Cultura classica' },
    { time: "12:38", id: "297eGtKQnoA", title: 'Carlo Magno Imperatore - Semeion - 2ª puntata', tag: 'Semeion - i simboli e la Storia' },
    { time: "13:18", id: "ktou5tayO18", title: 'Simbologia del Giudizio Universale di Michelangelo', tag: 'Simboli nell\'arte' },
    { time: "13:42", id: "y93e6we2ceo", title: 'I simboli sugli scudi nell\'Antica Grecia', tag: 'Semeion - i simboli e la Storia' },
    { time: "13:50", id: "E00Uh9R-ojI", title: 'Significati e simboli nella Madonna dei Pellegrini - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "14:08", id: "owZDKzZtEMo", title: 'Il mobile e la Storia', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "14:17", id: "H4YXia6yz-E", title: 'Vita medievale - Semeion - 4ª puntata', tag: 'Semeion - i simboli e la Storia' },
    { time: "14:54", id: "R1teLkuwotk", title: 'Simbologia di Venere e Marte - Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "15:14", id: "auWg9IHeDb8", title: 'La marchesa e le galline', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "15:24", id: "49NaNWgpT9c", title: 'La lampada e la sua simbologia', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "15:34", id: "t4bgM172WoY", title: 'Giotto - Il cielo stellato della Cappella degli Scrovegni - Padova', tag: 'Simboli nell\'arte' },
    { time: "15:59", id: "xCTDCGDexz4", title: 'Jacopo di Cione - Polittico di San Pier Maggiore', tag: 'Capolavori' },
    { time: "16:19", id: "72N4zH0uPok", title: 'Pieter Brueghel il Vecchio - Trionfo della Morte', tag: 'Simboli nell\'arte' },
    { time: "16:26", id: "NGY1ZCjtirA", title: 'L\'egida, la capra Amaltea e la cornucopia - I simboli e la storia', tag: 'Semeion - i simboli e la Storia' },
    { time: "16:32", id: "NjNjIxWSz4w", title: 'Gorgoneion - Le Gorgoni', tag: 'Semeion - i simboli e la Storia' },
    { time: "16:37", id: "LQVOt5DGEbc", title: 'Significati di Giustiniano e il suo seguito e il Corteo di Teodora in San Vitale', tag: 'Simboli nell\'arte' },
    { time: "17:09", id: "N5TveC0Jieo", title: 'Cima da Conegliano - Sant\'Elena', tag: 'Capolavori' },
    { time: "17:20", id: "V_G2rNyMWkA", title: 'Vittore Crivelli - Trittico di Monte San Martino', tag: 'Capolavori' },
    { time: "17:39", id: "DBRC_ndzw2o", title: 'Simbologia della Stanza della Segnatura - Raffaello', tag: 'Simboli nell\'arte' },
    { time: "18:29", id: "TjARMj13bPE", title: 'Il corsaro Landolfo e la cassetta', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "18:39", id: "3DSXSrLUTqA", title: 'Pignora imperii: i sette oggetti sacri di Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "18:49", id: "k51U0SrGnN4", title: 'Significati segreti della Pala Montefeltro - Piero della Francesca', tag: 'Simboli nell\'arte' },
    { time: "19:12", id: "wSGtfQhoMD0", title: 'Francesco del Cossa - Marzo nel Salone dei Mesi di Palazzo Schifanoia a Ferrara', tag: 'Capolavori' },
    { time: "19:34", id: "n3J2zHslid4", title: 'Simbologia del Peccato Originale e Cacciata dal Paradiso Terrestre', tag: 'Simboli nell\'arte' },
    { time: "20:00", id: "ElM7rPK06k8", title: 'Come mandare il diavolo all\'inferno', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "20:11", id: "mVOIPZpLdDk", title: 'Sandro Botticelli - Madonna col Bambino e due angeli [Capodimonte]', tag: 'Capolavori' },
    { time: "20:27", id: "vjejY2-VCFA", title: 'Simbologia delle Sibille alla Cappella Sistina - Michelangelo', tag: 'Simboli nell\'arte' },
    { time: "20:50", id: "t63MehZizgM", title: 'Sofonisba Anguissola, Le sorelle della pittrice Lucia, Minerva e Europa Anguissola giocano a scacchi', tag: 'Capolavori' },
    { time: "21:02", id: "2eNrA0pvehA", title: 'La sedia', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "21:40", id: "PqT2h3bHqPY", title: 'Simbologia del Ritratto dei coniugi Arnolfini - Jan van Eyck', tag: 'Simboli nell\'arte' },
    { time: "21:57", id: "egeEdEQFkT8", title: 'Il monaco e l\'abate', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "22:09", id: "6GAyi7t2Mmo", title: 'Giottino - Pietà di San Remigio', tag: 'Simboli nell\'arte' },
    { time: "22:21", id: "u-dUGWo5NoM", title: 'Maestro Venceslao - Luglio nel Ciclo dei Mesi di Torre Aquila', tag: 'Capolavori' },
    { time: "22:38", id: "Zr3BJG9najM", title: 'Jacomart Baço [attribuito] o Antonello da Messina [attribuito] - Madonna [Virgo advocata]', tag: 'Capolavori' },
    { time: "22:48", id: "XfFiEQ2preg", title: 'Giotto - Storie di San Francesco - Parte 3di3', tag: 'Simboli nell\'arte' },
    { time: "23:15", id: "GbXpfJo-Z6Y", title: 'Piero della Francesca - I duchi di Urbino Federico da Montefeltro e Battista Sforza', tag: 'Capolavori' },
    { time: "23:30", id: "tMU_pAxuuRc", title: 'Il mobile nell\'Arte', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "23:45", id: "jM3xyUde3YY", title: 'Piero della Francesca - Resurrezione', tag: 'Simboli nell\'arte' },
  ],
  5: [ // VENERDI
    { time: "07:58", id: "nRrWSTaabeQ", title: 'Inizio delle trasmissioni', tag: 'ARS EUROPA TV' },
    { time: "08:00", id: "h88VDynvAs0", title: 'Maestro Alberto e il porro', tag: 'Decameron - le novelle di Boccaccio' },
    { time: "08:09", id: "Cf2K8bmzNmY", title: 'Simbologia della Vocazione di San Matteo - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "08:32", id: "Y9ztKw9W1Sw", title: 'I consigli di PLATONE - l\'anima - FEDONE', tag: 'Cultura classica' },
    { time: "08:38", id: "JIDwzu-phUo", title: 'I consigli di Marco Aurelio - cooperazione', tag: 'Cultura classica' },
    { time: "08:45", id: "VrJp-1ZnnaM", title: 'Simbologia di Spes contra Spem di Renato Guttuso', tag: 'Simboli nell\'arte' },
    { time: "08:59", id: "VpLLY5D7M1E", title: 'Bronzino - Ritratto di Laura Battiferri', tag: 'Capolavori' },
    { time: "09:12", id: "HC6TWhk1lk8", title: 'ANKH - La croce della vita - I simboli dell\'antico Egitto', tag: 'Semeion - i simboli e la Storia' },
    { time: "09:20", id: "vf7owO-7PgY", title: 'Simbologia de LA MADONNA DEL MAGNIFICAT -  Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "09:35", id: "xeHuZbgtj6M", title: 'I consigli di CICERONE -- le aspettative', tag: 'Cultura classica' },
    { time: "09:42", id: "ZPxrf6U1ygM", title: 'Colijn de Coter - Polittico della Crocifissione - 1500 circa - Museo Nazionale Varsavia', tag: 'Capolavori' },
    { time: "09:52", id: "yDNaMmqGxYA", title: 'Simbologia di san Martino divide il mantello - Simone Martini', tag: 'Simboli nell\'arte' },
    { time: "10:04", id: "CvAgf2Ma_L0", title: 'I consigli di Seneca - La sobrietà - Lettere a Lucilio', tag: 'Cultura classica' },
    { time: "10:10", id: "e4C481L2uLw", title: 'Significati nascosti ne La Vanità - Bernardo Strozzi', tag: 'Simboli nell\'arte' },
    { time: "10:20", id: "tH-9bTMomV8", title: 'Francis Bacon - Studio per una corrida n°2', tag: 'Capolavori' },
    { time: "10:28", id: "jNGOdGlE7LQ", title: 'La Lupa - I Simboli e la Storia dell\'Antica Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "10:36", id: "g6FaZd1AvJs", title: 'Significato della Madonna con Bambino - Andrea Mantegna', tag: 'Simboli nell\'arte' },
    { time: "10:47", id: "LTmiNv4V0FM", title: 'La lampada nell\'Arte', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "11:00", id: "MLF8Po4J-Yk", title: 'I simboli e la Storia - Antica Roma - Le legioni', tag: 'Semeion - i simboli e la Storia' },
    { time: "11:08", id: "YacyxfzEqPQ", title: 'Giotto - Fasce ornamentali della Cappella degli Scrovegni - Padova', tag: 'Simboli nell\'arte' },
    { time: "11:19", id: "1oMoXawAhUs", title: 'Il serpente nell\'antica Grecia', tag: 'Semeion - i simboli e la Storia' },
    { time: "11:28", id: "2-MPaKWHva0", title: 'Simbologia del Polittico dell\'Agnello Mistico - Jan e Hubert van Eyck', tag: 'Simboli nell\'arte' },
    { time: "11:56", id: "se06EQ6E364", title: 'San Girolamo nello studio di Antonello da Messina', tag: 'Capolavori' },
    { time: "12:03", id: "_UBPKd5YdI0", title: 'I consigli di AGOSTINO - l\'oroscopo e le previsioni astrologiche', tag: 'Cultura classica' },
    { time: "12:09", id: "TAwg-YgcPY0", title: 'Simbologia della Vergine delle Rocce - Leonardo da Vinci', tag: 'Simboli nell\'arte' },
    { time: "12:23", id: "6NIGPkjTJf8", title: 'I consigli di Seneca - i luoghi dello spirito', tag: 'Cultura classica' },
    { time: "12:29", id: "-kT2WSjxw20", title: 'L\'ulivo, la civetta e il serpente - I Simboli e la Storia', tag: 'Semeion - i simboli e la Storia' },
    { time: "12:37", id: "LJhqbisWMJs", title: 'Significati nascosti nella Battaglia di Ponte Milvio - Piero della Francesca', tag: 'Simboli nell\'arte' },
    { time: "12:49", id: "CJIyeaOe1M8", title: 'I simboli sacri nel Medioevo', tag: 'Semeion - i simboli e la Storia' },
    { time: "12:58", id: "lCvCfNOJUlM", title: 'Giotto - Dio Padre e l’Annunciazione nella Cappella degli Scrovegni', tag: 'Simboli nell\'arte' },
    { time: "13:10", id: "xLiWCB2m9Jg", title: 'I simboli sacerdotali nell\'antica Roma', tag: 'Semeion - i simboli e la Storia' },
    { time: "13:21", id: "166JgZoFqjI", title: 'I racconti di Sallustio - ritratto di Catilina', tag: 'Cultura classica' },
    { time: "13:26", id: "gTKMLCt9YYo", title: 'Adorazione dei Magi di Gentile da Fabriano', tag: 'Simboli nell\'arte' },
    { time: "13:40", id: "UMPd8bSHfKI", title: 'I RACCONTI DI PLUTARCO - Vita di Cicerone - Infanzia e giovinezza', tag: 'Cultura classica' },
    { time: "13:49", id: "GuO9M2C4R-4", title: 'La lampada e il design', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "13:56", id: "YU1IkrgML_s", title: 'Giotto - Cappella degli Scrovegni', tag: 'Simboli nell\'arte' },
    { time: "17:06", id: "Cy1rxcIA3ZY", title: 'I consigli di PLATONE - l\'ALDILA\' e il giudizio', tag: 'Cultura classica' },
    { time: "17:13", id: "s6QnfgVPxZA", title: 'I simboli dell\'alchimia nel Medioevo', tag: 'Semeion - i simboli e la Storia' },
    { time: "17:21", id: "0hpZAYhWJZc", title: 'Significati nascosti nell\'Allegoria della Prudenza - Tiziano', tag: 'Simboli nell\'arte' },
    { time: "17:33", id: "vSuK0ce-bl4", title: 'Il mobile e il design', tag: 'SIGN&DESIGN - Storia e simboli degli oggetti di moda, lusso e design' },
    { time: "17:42", id: "6yM8VKnx1D4", title: 'Simbologia del GIUDIZIO UNIVERSALE - Giotto', tag: 'Simboli nell\'arte' },
    { time: "17:57", id: "ysrwIZBk7jM", title: 'Sofonisba Anguissola - Sposalizio mistico di Santa Caterina', tag: 'Capolavori' },
    { time: "18:08", id: "IjEmsqnsHKY", title: 'L\'invincibile esercito romano - Semeion - 1ª puntata', tag: 'Semeion - i simboli e la Storia' },
    { time: "18:41", id: "hRWGacsblOE", title: 'Simbologia del ciclo di San Matteo alla Cappella Contarelli - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "20:03", id: "187m12rc8iE", title: 'I simboli delle corporazioni medievali', tag: 'Semeion - i simboli e la Storia' },
    { time: "20:13", id: "PBQpaPQeVnk", title: 'Vittore Crivelli - Polittico di Monte San Martino', tag: 'Capolavori' },
    { time: "20:21", id: "ysWTYu_xWeE", title: 'Simbologia di Amor Sacro e Amor Profano - Tiziano', tag: 'Simboli nell\'arte' },
    { time: "20:43", id: "UU9BLVei6QU", title: 'L\'occhio di Horus -  Antico Egitto', tag: 'Semeion - i simboli e la Storia' },
    { time: "20:57", id: "GFUEEsgNIAU", title: 'Significati nascosti nella Primavera - Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "21:34", id: "mwSAxNQ_re0", title: 'Società dell\'antica Roma - Semeion - 5ª puntata', tag: 'Semeion - i simboli e la Storia' },
    { time: "22:14", id: "0ftfDKWeYS0", title: 'I consigli di OVIDIO - agli uomini - ARS AMANDI', tag: 'Cultura classica' },
    { time: "22:21", id: "zJwo2Yvtcns", title: 'Simbologia di Ritratto di vecchio e nipote - Domenico Ghirlandaio', tag: 'Simboli nell\'arte' },
    { time: "22:30", id: "zoeXahpnNBA", title: 'Maestro Venceslao - Novembre nel Ciclo dei Mesi di Torre Aquila - Trento', tag: 'Capolavori' },
    { time: "22:46", id: "SZpEXt_R8-E", title: 'Maestro Venceslao - Maggio nel Ciclo dei Mesi di Torre Aquila', tag: 'Capolavori' },
    { time: "23:01", id: "H23ssQtI0VA", title: 'Simbologia nascosta nel mosaico absidale di Santa Maria in Trastevere', tag: 'Simboli nell\'arte' },
    { time: "23:27", id: "5ice597_aGU", title: 'Antonello da Messina - Crocifissione di Sibiu', tag: 'Capolavori' },
    { time: "23:45", id: "Yxp4kXLBVsE", title: 'Simbologia de La barca di Dante - Eugène Delacroix', tag: 'Simboli nell\'arte' },
  ],
  6: [ // SABATO
    { time: "07:58", id: "nRrWSTaabeQ", title: 'Inizio delle trasmissioni', tag: 'ARS EUROPA TV' },
    { time: "08:00", id: "p_XU7vqtsic", title: 'Simbologia di Giugno a Palazzo Schifanoia', tag: 'Capolavori' },
    { time: "08:17", id: "WA0-DSA8TTI", title: 'Lorenzo D\'Alessandro - Matrimonio mistico di Santa Caterina da Siena', tag: 'Capolavori' },
    { time: "08:37", id: "H9XFulxh-2Q", title: 'Giotto - Maestà di Ognissanti - Uffizi - Firenze', tag: 'Simboli nell\'arte' },
    { time: "09:19", id: "mNbR-hfE2gc", title: 'Bronzino - Ritratto di Eleonora di Toledo con il figlio Giovanni', tag: 'Capolavori' },
    { time: "09:33", id: "md0SomPZXx0", title: 'Leonardo da Vinci - Adorazione dei Magi', tag: 'Capolavori' },
    { time: "09:52", id: "WKNbx0R0UA4", title: 'Hans Memling - Passione di Cristo', tag: 'Simboli nell\'arte' },
    { time: "10:06", id: "Vxbslrddq_c", title: 'Maestro Venceslao - Dicembre nel Ciclo dei Mesi di Torre Aquila', tag: 'Capolavori' },
    { time: "10:21", id: "-RVGqjxxauI", title: 'Jusepe de Ribera - San Francesco in meditazione', tag: 'Capolavori' },
    { time: "10:39", id: "e-3OgD1H4oc", title: 'Giotto - I simboli dei Vizi e delle Virtù nella Cappella degli Scrovegni', tag: 'Simboli nell\'arte' },
    { time: "10:52", id: "UBd5AuyEwjE", title: 'Beato Angelico - Trittico [Ascensione, Giudizio Finale, Pentecoste]', tag: 'Capolavori' },
    { time: "11:17", id: "3aA0vZ2GOgA", title: 'Simbologia di NOTTE STELLATA -  Vincent Van Gogh', tag: 'Simboli nell\'arte' },
    { time: "11:23", id: "zwMEiAsWU6c", title: 'Cimabue - Crocifissione del transetto sinistro della Basilica Superiore di San Francesco', tag: 'Capolavori' },
    { time: "11:36", id: "7cNggvoR4PM", title: 'Simone Martini e Lippo Memmi - Annunciazione e i santi Ansano e Massima - Uffizi', tag: 'Capolavori' },
    { time: "11:44", id: "6SA6cM9yCdU", title: 'Simbologia di Giovane introdotto tra le Arti Liberali - Botticelli', tag: 'Simboli nell\'arte' },
    { time: "11:53", id: "kFImaLcpJlE", title: 'Lorenzo d’Alessandro - Madonna con Bambino e santi [Polittico di Serrapetrona]', tag: 'Capolavori' },
    { time: "12:06", id: "XgBJ4gwE_gI", title: 'Duccio di Buoninsegna - La Natività con i profeti Isaia ed Ezechiele', tag: 'Capolavori' },
    { time: "12:26", id: "E-KVIKmIqFc", title: 'Simbologia di Venere che benda Amore - Tiziano', tag: 'Simboli nell\'arte' },
    { time: "12:34", id: "_q6V_Iv9eWs", title: 'Il Battesimo di Cristo di Andrea del Verrocchio e Leonardo', tag: 'Capolavori' },
    { time: "12:44", id: "KSBQ09SX4Gs", title: 'Significati nascosti ne Le due Trinità - Bartolomé Esteban Murillo', tag: 'Simboli nell\'arte' },
    { time: "12:58", id: "u1GPCMfYTbE", title: 'Il Polittico di Giovanni Boccati nella Chiesa di Sant’Eustachio a Belforte del Chienti', tag: 'Capolavori' },
    { time: "13:09", id: "wUq4gBzfZ8E", title: 'Sofonisba Anguissola - Ritratto di Bianca Ponzoni Anguissola', tag: 'Capolavori' },
    { time: "13:18", id: "yxvsxQdfWLU", title: 'Significati nascosti nella Resurrezione di Cristo - Andrea Mantegna', tag: 'Simboli nell\'arte' },
    { time: "13:31", id: "RxPRrZcmAuQ", title: 'Domenico Ghirlandaio - Sacra conversazione degli Ingesuati', tag: 'Capolavori' },
    { time: "13:49", id: "6xVARIRjoI8", title: 'Simbologia di Settembre - Palazzo Schifanoia', tag: 'Capolavori' },
    { time: "14:12", id: "7ZRo9cVIazE", title: 'Giotto - Storie di San Francesco - Parte 2di3', tag: 'Simboli nell\'arte' },
    { time: "14:31", id: "bdrOIWKaZ0Y", title: 'Pietro Lorenzetti - Beata Umiltà e storie della sua vita', tag: 'Capolavori' },
    { time: "14:42", id: "YXKYiJ4vQjM", title: 'Simbologia de IL  BACIO -  Francesco Hayez', tag: 'Simboli nell\'arte' },
    { time: "14:55", id: "D0zSjqXl380", title: 'Georges Braque - Violino', tag: 'Capolavori' },
    { time: "15:03", id: "5-BgoO5nwyM", title: 'Andrea Mantegna - I trionfi di Giulio Cesare', tag: 'Capolavori' },
    { time: "15:25", id: "eTdJ1nws6yw", title: 'Simbologia de IL BACCHINO MALATO -  Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "15:35", id: "Tuf5lu30V0M", title: 'Pietro Cavallini - Giudizio Universale', tag: 'Capolavori' },
    { time: "15:48", id: "11vBcPoS0fA", title: 'Maestro Venceslao - Gennaio nel ciclo dei mesi della Torre Aquila a Trento', tag: 'Capolavori' },
    { time: "15:56", id: "pXvP8sc5UV8", title: 'Simbologia della Madonna della melagrana - Sandro Botticelli', tag: 'Simboli nell\'arte' },
    { time: "16:16", id: "MbRcDJGh3DI", title: 'Tintoretto - Crocifissione', tag: 'Capolavori' },
    { time: "16:21", id: "lQXldgGGJvQ", title: 'Maestro Venceslao - Agosto nel Ciclo dei Mesi della Torre Aquila a Trento', tag: 'Capolavori' },
    { time: "16:29", id: "TE2IMczLzZ8", title: 'Significati nascosti ne Le opere della Misericordia - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "16:50", id: "MCbc1uew3Ao", title: 'Maestro Venceslao - Ottobre nel Ciclo dei Mesi di Torre Aquila - Trento', tag: 'Capolavori' },
    { time: "17:05", id: "f6UQQmIgusI", title: 'Significati nascosti nei simboli nel Giardino delle delizie - Bosch', tag: 'Simboli nell\'arte' },
    { time: "17:44", id: "bmc0TcDXIVs", title: 'Maestro Venceslao [e Marcello Fogolino] - Giugno nel Ciclo dei Mesi di Torre Aquila', tag: 'Capolavori' },
    { time: "18:00", id: "_l9LAjrgZl8", title: 'Antonello da Messina - Ritratto d’uomo', tag: 'Capolavori' },
    { time: "18:16", id: "2L2vi4hEwvI", title: 'Significato dei simboli nel Cristo Cosmocratore - San Vitale a Ravenna', tag: 'Simboli nell\'arte' },
    { time: "18:35", id: "mwBR1q1ezYM", title: 'Piero del Pollaiolo - Pala del cardinale del Portogallo', tag: 'Capolavori' },
    { time: "18:44", id: "EJcAT-aYu18", title: 'Carlo e Vittore Crivelli - Polittico di Monte San Martino', tag: 'Capolavori' },
    { time: "18:55", id: "vbIKfQBQBn0", title: 'Agosto negli Arazzi Trivulzio - Bramantino e Manifattura di Vigevano', tag: 'Simboli nell\'arte' },
    { time: "19:10", id: "768EpeGUgzI", title: 'Maestro Venceslao - Aprile nel Ciclo dei Mesi di Torre Aquila', tag: 'Capolavori' },
    { time: "19:24", id: "i4jGjxC-qbE", title: 'Giotto - Storie di San Francesco - Parte 1di3', tag: 'Simboli nell\'arte' },
    { time: "19:57", id: "55aKom1mDB0", title: 'Giovan Francesco Barbieri detto Il Guercino - L\'angelo custode', tag: 'Capolavori' },
    { time: "20:09", id: "dBcoGyxSSQ0", title: 'Donatello - Maddalena penitente', tag: 'Capolavori' },
    { time: "20:18", id: "ETfIifBy_Ck", title: 'Sandro Botticelli - Annunciazione di Cestello', tag: 'Simboli nell\'arte' },
    { time: "20:28", id: "4MbscGhd_yw", title: 'Bartolomé Bermejo - Trittico della Vergine di Montserrat', tag: 'Capolavori' },
    { time: "20:45", id: "U1d__WRatso", title: 'Simone Martini e Lippo Memmi - Annunciazione e i santi Ansano e Massima', tag: 'Capolavori' },
    { time: "21:00", id: "gW7A_NVA8h8", title: 'Simbologia della Creazione di Adamo - Michelangelo', tag: 'Simboli nell\'arte' },
    { time: "21:23", id: "6yeJTsyKUMo", title: 'Duccio di Buoninsegna - Annunciazione', tag: 'Capolavori' },
    { time: "21:36", id: "hwuth8AkzkA", title: 'Beato Angelico - Discesa agli Inferi', tag: 'Simboli nell\'arte' },
    { time: "22:00", id: "Y0nKHG5lCiM", title: 'Simbologia di Luglio - Palazzo Schifanoia', tag: 'Capolavori' },
    { time: "22:22", id: "6hiMdJj9TTk", title: 'Simbologia di Maggio a Palazzo Schifanoia', tag: 'Capolavori' },
    { time: "22:35", id: "hnhA6JNWnZI", title: 'Significato del Sacrificio di Isacco - Caravaggio', tag: 'Simboli nell\'arte' },
    { time: "22:45", id: "LIKOP__oc7I", title: 'Giotto - Crocifisso di Padova', tag: 'Capolavori' },
    { time: "23:08", id: "JMaQPHh9MD4", title: 'Cristoforo di Bindoccio e Meo di Pero - Ruote di Barlaam e Aristotele in Palazzo Corboli ad Asciano', tag: 'Capolavori' },
  ],
};