const schedules = {
  0: [ // DOMENICA
    { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio delle trasmissioni", tag: "ARS EUROPA TV" },
    { time: "08:02", id: "8f5m0M3rmIA", title: "Giotto - Storie di San Francesco - Assisi", tag: "Simboli nell'Arte" },
    { time: "09:12", id: "Dm5ND9wQNKk", title: "Quarta puntata - Antropotesi - Né Apocalittici né Integrati", tag: "Né Apocalittici né Integrati" },
    { time: "09:30", id: "EUKj2MyULiw", title: "Apocalisse: le ultime parole di Dio", tag: "Sacrum" },
    { time: "10:20", id: "CKjDj0O-D4o", title: "ANTONIO, Abbà - L'eremita che inventò il monachesimo", tag: "Historica" },
    { time: "10:38", id: "gYZlbiG0Mk4", title: "Edipo a Colono - Sofocle", tag: "Teatro Greco" },
    { time: "11:27", id: "b0gBKKEZTA8", title: "L'usuraio, l'abate e la fanciulla", tag: "Decameron" },
    { time: "11:45", id: "S409sg6u1_M", title: "PIRANDELLO: una, nessuna, centomila maschere. E la tua qual è?", tag: "I principi della poesia" },
    { time: "12:25", id: "KIPYOCWYVSU", title: "GIOVANNI, lo sguardo dell'aquila", tag: "Tetramorfo" },
    { time: "12:42", id: "FQPe1qoCQI8", title: "Simbologia dei Profeti alla Cappella Sistina - Michelangelo", tag: "Simboli nell'Arte" },
    { time: "13:22", id: "8RHc0dwAVmE", title: "Orfeo", tag: "Simboli, miti e leggende" },
    { time: "13:39", id: "FyOCxDBzYIE", title: "Simbologia delle sette Virtù - Pollaiolo e Botticelli", tag: "Simboli nell'Arte" },
    { time: "14:13", id: "yUEMOT8J8KU", title: "Giandomenico Tiepolo - Scena di Carnevale [Il minuetto]", tag: "Capolavori" },
    { time: "14:29", id: "IjEmsqnsHKY", title: "L'invincibile esercito romano - Semeion - 1ª puntata", tag: "Semeion" },
    { time: "15:02", id: "mVOIPZpLdDk", title: "Sandro Botticelli - Madonna col Bambino e due angeli [Capodimonte]", tag: "Capolavori" },
    { time: "15:18", id: "LBdvcDAlFjM", title: "Filottete  - Sofocle", tag: "Teatro Greco" },
    { time: "15:50", id: "tMU_pAxuuRc", title: "Il mobile nell'Arte", tag: "SIGN&DESIGN" },
    { time: "16:05", id: "GrqPGuz1N-A", title: "Antigone - Sofocle", tag: "Teatro Greco" },
    { time: "16:35", id: "U1d__WRatso", title: "Simone Martini e Lippo Memmi - Annunciazione e i santi Ansano e Massima", tag: "Capolavori" },
    { time: "16:50", id: "9wxNflU3IFQ", title: "I Persiani -  Eschilo", tag: "Teatro Greco" },
    { time: "17:19", id: "zrSkcpDgWuw", title: "La Cattedrale di Notre-Dame di Parigi", tag: "I luoghi, simboli e Storia" },
    { time: "17:32", id: "n3J2zHslid4", title: "Simbologia del Peccato Originale e Cacciata dal Paradiso Terrestre", tag: "Simboli nell'Arte" },
    { time: "17:58", id: "VpLLY5D7M1E", title: "Bronzino - Ritratto di Laura Battiferri", tag: "Capolavori" },
    { time: "18:11", id: "SxTPMNST8Q4", title: "Le Supplici - Eschilo", tag: "Teatro Greco" },
    { time: "18:36", id: "86HxQMkRBfo", title: "Le festività nell'antica Roma", tag: "Semeion" },
    { time: "18:49", id: "JBxkizfcJno", title: "Andreuccio da Perugia e la sorella ritrovata", tag: "Decameron" },
    { time: "19:13", id: "WE4mzzXcPbo", title: "Canto XI - Inferno - Viaggio nell'aldilà", tag: "Divina Commedia" },
    { time: "19:25", id: "gW7A_NVA8h8", title: "Simbologia della Creazione di Adamo - Michelangelo", tag: "Simboli nell'Arte" },
    { time: "19:48", id: "QcN8IL5cGiI", title: "Crisippo", tag: "Philosophia" },
    { time: "20:00", id: "4O8X48ICIaw", title: "I sette contro Tebe - Eschilo", tag: "Teatro Greco" },
    { time: "20:23", id: "t63MehZizgM", title: "Sofonisba Anguissola, Le sorelle della pittrice Lucia, Minerva e Europa Anguissola giocano a scacchi", tag: "Capolavori" },
    { time: "20:35", id: "vjejY2-VCFA", title: "Simbologia delle Sibille alla Cappella Sistina - Michelangelo", tag: "Simboli nell'Arte" },
    { time: "20:58", id: "dESyuomRI3E", title: "I profeti di BAAL e il doppio olocausto", tag: "Storie dalla Bibbia" },
    { time: "21:09", id: "YguWYzvu7Jk", title: "Giuffredi, il figlio della Capriola", tag: "Decameron" },
    { time: "21:29", id: "ElM7rPK06k8", title: "Come mandare il diavolo all'inferno", tag: "Decameron" },
    { time: "21:40", id: "xLiWCB2m9Jg", title: "I simboli sacerdotali nell'antica Roma", tag: "Semeion" },
    { time: "21:51", id: "S80kNQbbpNk", title: "Anassimandro e l'apeiron", tag: "Philosophia" },
    { time: "22:02", id: "uLLIhAn0DJM", title: "I simboli dei cavalieri medievali - Semeion, i Simboli e la Storia", tag: "Semeion" },
    { time: "22:13", id: "Zr3BJG9najM", title: "Jacomart Baço [attribuito] o Antonello da Messina [attribuito] - Madonna [Virgo advocata]", tag: "Capolavori" },
    { time: "22:23", id: "TjARMj13bPE", title: "Il corsaro Landolfo e la cassetta", tag: "Decameron" },
    { time: "22:33", id: "3DSXSrLUTqA", title: "Pignora imperii: i sette oggetti sacri di Roma", tag: "Semeion" },
    { time: "22:43", id: "8tkD5HhoxYM", title: "Chichibìo e la gru", tag: "Decameron" },
    { time: "22:52", id: "oqTUTClIW2I", title: "Aristotele", tag: "Philosophia" },
    { time: "23:01", id: "Pkmfnn3KcWM", title: "Talete e l'acqua", tag: "Philosophia" },
    { time: "23:10", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria", tag: "Philosophia" },
    { time: "23:18", id: "JIDwzu-phUo", title: "I consigli di Marco Aurelio - cooperazione", tag: "Cultura classica" },
    { time: "23:25", id: "K1vFnkYUA6c", title: "I simboli dei sottufficiali romani", tag: "Semeion" },
    { time: "23:32", id: "4JhzDRygmAI", title: "I consigli di CICERONE - il valore dell'amicizia - De Amicitia", tag: "Cultura classica" },
    { time: "23:39", id: "jtStIm5z7II", title: "I consigli di Seneca - Amicizia", tag: "Cultura classica" },
    { time: "23:46", id: "0Q3UHX75roM", title: "I consigli di AGOSTINO - la felicità - le Confessioni", tag: "Cultura classica" },
    { time: "23:52", id: "Y9ztKw9W1Sw", title: "I consigli di PLATONE - l'anima - FEDONE", tag: "Cultura classica" },
    { time: "23:58", id: "enm0U_D3EpE", title: "ENEIDE - Enea racconta la caduta di Troia - prima parte", tag: "Eneide" },
  ],
  1: [ // LUNEDI
    { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio delle trasmissioni", tag: "ARS EUROPA TV" },
    { time: "08:02", id: "7_LUxivWuAM", title: "LE TROIANE - Euripide", tag: "Teatro Greco" },
    { time: "09:01", id: "md0SomPZXx0", title: "Leonardo da Vinci - Adorazione dei Magi", tag: "Capolavori" },
    { time: "09:20", id: "TNlYUDPzZtg", title: "ANDROMACA - Euripide", tag: "Teatro Greco" },
    { time: "10:10", id: "xKRU6UqRLTQ", title: "Le Eumenidi - Eschilo", tag: "Teatro Greco" },
    { time: "10:29", id: "EhsO8Dea9yM", title: "ECUBA - Euripide", tag: "Teatro Greco" },
    { time: "11:17", id: "VzG3biTZ1rg", title: "Agamennone  -  Eschilo", tag: "Teatro Greco" },
    { time: "11:35", id: "jJpr7Ttffks", title: "Dante Alighieri - Tra terra e cielo - I principi della poesia", tag: "I principi della poesia" },
    { time: "12:13", id: "i4hB8HMOSW8", title: "Giovanni Bellini - Polittico di San Vincenzo Ferrer", tag: "Capolavori" },
    { time: "12:31", id: "_AHY1IOE1Hg", title: "I Demoni", tag: "Sacrum" },
    { time: "13:01", id: "_33jtBhONO0", title: "Coefore - Eschilo", tag: "Teatro Greco" },
    { time: "13:18", id: "BpfNVrGJreE", title: "Prometeo Incatenato - Eschilo", tag: "Teatro Greco" },
    { time: "13:43", id: "4MbscGhd_yw", title: "Bartolomé Bermejo - Trittico della Vergine di Montserrat", tag: "Capolavori" },
    { time: "14:00", id: "JMaQPHh9MD4", title: "Cristoforo di Bindoccio e Meo di Pero - Ruote di Barlaam e Aristotele in Palazzo Corboli ad Asciano", tag: "Capolavori" },
    { time: "14:23", id: "djHOf0ETZjk", title: "Quinta puntata - il racconto senza storia - Né Apocalittici né Integrati", tag: "Né Apocalittici né Integrati" },
    { time: "14:39", id: "ysWTYu_xWeE", title: "Simbologia di Amor Sacro e Amor Profano - Tiziano", tag: "Simboli nell'Arte" },
    { time: "15:01", id: "Brwji6geGWQ", title: "Matteo, la mano dell'angelo", tag: "Tetramorfo" },
    { time: "15:17", id: "3aUGhajRXBA", title: "Simbologia della Messa di Bolsena - Raffaello", tag: "Simboli nell'Arte" },
    { time: "15:38", id: "DMJU2D2BxOg", title: "Simbologia dell'Annunciata di Palermo - Antonello da Messina", tag: "Simboli nell'Arte" },
    { time: "15:52", id: "0UOJdSzhFrI", title: "Teti", tag: "Simboli, miti e leggende" },
    { time: "16:12", id: "VrJp-1ZnnaM", title: "Simbologia di Spes contra Spem di Renato Guttuso", tag: "Simboli nell'Arte" },
    { time: "16:26", id: "XgBJ4gwE_gI", title: "Duccio di Buoninsegna - La Natività con i profeti Isaia ed Ezechiele", tag: "Capolavori" },
    { time: "16:46", id: "-g9dPd7B4uA", title: "Simbologia della Battaglia di Costantino contro Massenzio - Scuola di Raffaello", tag: "Simboli nell'Arte" },
    { time: "17:00", id: "R1teLkuwotk", title: "Simbologia di Venere e Marte - Sandro Botticelli", tag: "Simboli nell'Arte" },
    { time: "17:20", id: "Vjes7xPZgo0", title: "Calandrino incinto", tag: "Decameron" },
    { time: "17:34", id: "FyYCrzZPETI", title: "Canto XII Inferno - Viaggio nell'Aldilà", tag: "Divina Commedia" },
    { time: "17:47", id: "5DtPo9q0YJo", title: "VALENTINO, un amore trascendente", tag: "Historica" },
    { time: "18:00", id: "MAx6zDUILbQ", title: "Zenone e i suoi paradossi", tag: "Philosophia" },
    { time: "18:13", id: "Mz-gYg4bV0Y", title: "Duccio di Buoninsegna - Madonna con il Bambino e sei angeli", tag: "Capolavori" },
    { time: "18:26", id: "5D0qcufRzOw", title: "Bergamino e l'avarizia di Cangrande", tag: "Decameron" },
    { time: "18:39", id: "kFImaLcpJlE", title: "Lorenzo d’Alessandro - Madonna con Bambino e santi [Polittico di Serrapetrona]", tag: "Capolavori" },
    { time: "18:52", id: "w1nyMgzoZQE", title: "Enea racconta la caduta di Troia -  quarta parte - L'INCENDIO", tag: "Eneide" },
    { time: "19:04", id: "SOqN2uepscY", title: "Eraclito e il fuoco", tag: "Philosophia" },
    { time: "19:16", id: "55aKom1mDB0", title: "Giovan Francesco Barbieri detto Il Guercino - L'angelo custode", tag: "Capolavori" },
    { time: "19:28", id: "MYEi1LhYlo4", title: "PROTAGORA e le antilogie", tag: "Philosophia" },
    { time: "19:40", id: "M3SAVcBKSW4", title: "Simbologia della Lippina - Filippo Lippi", tag: "Simboli nell'Arte" },
    { time: "19:52", id: "aWlHf7nx3Z8", title: "San Giuliano, il mercante e la vedovella", tag: "Decameron" },
    { time: "20:03", id: "5BJaK2Nv3L0", title: "Empedocle e i quattro elementi", tag: "Philosophia" },
    { time: "20:14", id: "KvpEM4bgfZY", title: "Anassagora e il Nous", tag: "Philosophia" },
    { time: "20:25", id: "pqFlJHOibGI", title: "Democrito e gli atomi", tag: "Philosophia" },
    { time: "20:36", id: "La8RbJbSL6U", title: "Pitagora e i numeri", tag: "Philosophia" },
    { time: "20:46", id: "9BETjtp1mbA", title: "Parmenide e l'Essere", tag: "Philosophia" },
    { time: "20:56", id: "E3bNrJqqvjQ", title: "Amuleti e talismani nell'antica Roma", tag: "Semeion" },
    { time: "21:06", id: "bSIeXu1fmZw", title: "Simbologia dell'abbigliamento maschile nell'antica Roma", tag: "Semeion" },
    { time: "21:16", id: "auWg9IHeDb8", title: "La marchesa e le galline", tag: "Decameron" },
    { time: "21:26", id: "ISGDp4oMwPM", title: "Simbologia dell'Incendio di Borgo - Raffaello", tag: "Simboli nell'Arte" },
    { time: "21:36", id: "_noxbELcGdc", title: "Il Pantheon", tag: "I luoghi, simboli e Storia" },
    { time: "21:45", id: "vSuK0ce-bl4", title: "Il mobile e il design", tag: "SIGN&DESIGN" },
    { time: "21:54", id: "JlDzVj7QrZM", title: "SAMUELE e la voce misteriosa", tag: "Storie dalla Bibbia" },
    { time: "22:03", id: "1oMoXawAhUs", title: "Il serpente nell'antica Grecia", tag: "Semeion" },
    { time: "22:12", id: "PeDzAGHnkLw", title: "Il frate avido e la brodaglia dei poveri", tag: "Decameron" },
    { time: "22:21", id: "7Y3g-9sAX2g", title: "Il segno del comando nell'Antica Roma", tag: "Semeion" },
    { time: "22:29", id: "3pjCAAs55xo", title: "I consigli di CICERONE - Le forze nella vecchiaia", tag: "Cultura classica" },
    { time: "22:37", id: "h2SSOHy_LQg", title: "Erminio Avarizia", tag: "Decameron" },
    { time: "22:45", id: "EVNS93JNpUM", title: "I simboli nei mosaici romani", tag: "Semeion" },
    { time: "22:53", id: "y93e6we2ceo", title: "I simboli sugli scudi nell'Antica Grecia", tag: "Semeion" },
    { time: "23:01", id: "HC6TWhk1lk8", title: "ANKH - La croce della vita - I simboli dell'antico Egitto", tag: "Semeion" },
    { time: "23:09", id: "Cy1rxcIA3ZY", title: "I consigli di PLATONE - l'ALDILA' e il giudizio", tag: "Cultura classica" },
    { time: "23:16", id: "xeHuZbgtj6M", title: "I consigli di CICERONE -- le aspettative", tag: "Cultura classica" },
    { time: "23:23", id: "j-QqaWgK3rA", title: "I consigli di Marco Aurelio - Il giusto atteggiamento - Meditazioni", tag: "Cultura classica" },
    { time: "23:29", id: "6NIGPkjTJf8", title: "I consigli di Seneca - i luoghi dello spirito", tag: "Cultura classica" },
    { time: "23:35", id: "_UBPKd5YdI0", title: "I consigli di AGOSTINO - l'oroscopo e le previsioni astrologiche", tag: "Cultura classica" },
    { time: "23:41", id: "1JTtwMU3W4c", title: "Cyrano de Bergerac - Edmond Rostand, Non, merci - No, grazie", tag: "Poesia" },
    { time: "23:46", id: "9e4uCJAmljA", title: "La dama di Guascogna e il re di Cipro", tag: "Decameron" },
    { time: "23:51", id: "lBnP772e7AA", title: "I consigli di PLATONE - le buone discussioni", tag: "Cultura classica" },
    { time: "23:56", id: "YEmpT3udO4U", title: "I consigli di Seneca - la virtù - Lettere a Lucilio", tag: "Cultura classica" },
  ],
  2: [ // MARTEDI
    { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio delle trasmissioni", tag: "ARS EUROPA TV" },
    { time: "08:02", id: "UUSpcCJPgA8", title: "I PUNTI CARDINALI DELL'ISPIRAZIONE  -  Giuseppe Ungaretti -  I principi della poesia", tag: "I principi della poesia" },
    { time: "09:15", id: "dyHRAo_bOjA", title: "Né Apocalittici né Integrati - Prima puntata - la terza via dell'Intelligenza Artificiale", tag: "Né Apocalittici né Integrati" },
    { time: "09:33", id: "Z2ibq-HfwiI", title: "I simboli di Raffaello - Viaggio nei significati alle Scuderie del Quirinale", tag: "Simboli nell'Arte" },
    { time: "10:28", id: "wStQPVyWzuM", title: "Ser Ciappelletto", tag: "Decameron" },
    { time: "10:46", id: "vtJGNqiVUho", title: "IPPOLITO - Euripide", tag: "Teatro Greco" },
    { time: "11:38", id: "kjDXf0ndIWY", title: "Canto XIII - Inferno - Viaggio nell'aldilà", tag: "Divina Commedia" },
    { time: "11:54", id: "DBRC_ndzw2o", title: "Simbologia della Stanza della Segnatura - Raffaello", tag: "Simboli nell'Arte" },
    { time: "12:44", id: "pVOr0QbCOZA", title: "CATERINA, la forza della Sapienza", tag: "Historica" },
    { time: "13:00", id: "gvBOqwT-iJ0", title: "Ifigenia in Aulide - Euripide", tag: "Teatro Greco" },
    { time: "13:46", id: "dHmkQOcHcrY", title: "Il Colosseo", tag: "I luoghi, simboli e Storia" },
    { time: "14:00", id: "_5mO9eF7OzA", title: "IFIGENIA IN TAURIDE - Euripide", tag: "Teatro Greco" },
    { time: "14:43", id: "TAwg-YgcPY0", title: "Simbologia della Vergine delle Rocce - Leonardo da Vinci", tag: "Simboli nell'Arte" },
    { time: "14:57", id: "JxHiv1EbEXY", title: "Aiace - Sofocle", tag: "Teatro Greco" },
    { time: "15:40", id: "WKNbx0R0UA4", title: "Hans Memling - Passione di Cristo", tag: "Capolavori" },
    { time: "15:54", id: "VNx-F7naSK0", title: "ELETTRA -  Sofocle", tag: "Teatro Greco" },
    { time: "16:32", id: "nji3BUHv_Fs", title: "MARCO, il leone della fede", tag: "Tetramorfo" },
    { time: "16:45", id: "eSQcTSW5u50", title: "ALCESTI -  Euripide", tag: "Teatro Greco" },
    { time: "17:16", id: "msTcwXQM3Qs", title: "GORGIA e la parola", tag: "Philosophia" },
    { time: "17:29", id: "uaSEfOUDRDo", title: "Edipo re - Sofocle", tag: "Teatro Greco" },
    { time: "17:50", id: "5coSTdhVpuU", title: "Platone", tag: "Philosophia" },
    { time: "18:03", id: "zOEB44h7S5k", title: "Medea - Euripide", tag: "Teatro Greco" },
    { time: "18:23", id: "Ukb7enwrhmU", title: "Martellino e il finto miracolo", tag: "Decameron" },
    { time: "18:36", id: "fqiHHH72OMs", title: "Simbologia di Madonna di Santa Trinita - Cimabue", tag: "Simboli nell'Arte" },
    { time: "18:48", id: "egeEdEQFkT8", title: "Il monaco e l'abate", tag: "Decameron" },
    { time: "19:00", id: "QcN8IL5cGiI", title: "Crisippo", tag: "Philosophia" },
    { time: "19:12", id: "9K_bfj937Pg", title: "Un mercante ebreo in Vaticano", tag: "Decameron" },
    { time: "19:24", id: "T9m9cm0dhWY", title: "Come attaccare la coda a una cavalla", tag: "Decameron" },
    { time: "19:36", id: "hU_Bq30AsNM", title: "Europa", tag: "Simboli, miti e leggende" },
    { time: "19:47", id: "mNenPBAaVvI", title: "Effetti del Buon Governo in città e in campagna - Ambrogio Lorenzetti", tag: "Simboli nell'Arte" },
    { time: "19:58", id: "bdrOIWKaZ0Y", title: "Pietro Lorenzetti - Beata Umiltà e storie della sua vita", tag: "Capolavori" },
    { time: "20:09", id: "S80kNQbbpNk", title: "Anassimandro e l'apeiron", tag: "Philosophia" },
    { time: "20:20", id: "_RqV9r-Wm74", title: "Lo Spirito Santo nel Cristianesimo", tag: "Sacrum" },
    { time: "20:30", id: "-SNEvPO-2D4", title: "Il mobile e la sua simbologia", tag: "SIGN&DESIGN" },
    { time: "20:40", id: "abUpEQBf1b0", title: "MENE,TEKEL,PERES - la mano fantasma", tag: "Storie dalla Bibbia" },
    { time: "20:50", id: "_57OfZukJTs", title: "Il Sultano Saladino e i tre anelli", tag: "Decameron" },
    { time: "21:00", id: "ETfIifBy_Ck", title: "Sandro Botticelli - Annunciazione di Cestello", tag: "Simboli nell'Arte" },
    { time: "21:10", id: "187m12rc8iE", title: "I simboli delle corporazioni medievali", tag: "Semeion" },
    { time: "21:20", id: "h88VDynvAs0", title: "Maestro Alberto e il porro", tag: "Decameron" },
    { time: "21:29", id: "CJIyeaOe1M8", title: "I simboli sacri nel Medioevo", tag: "Semeion" },
    { time: "21:38", id: "1zSwyFPn4Yk", title: "Socrate", tag: "Philosophia" },
    { time: "21:47", id: "wUq4gBzfZ8E", title: "Sofonisba Anguissola - Ritratto di Bianca Ponzoni Anguissola", tag: "Capolavori" },
    { time: "21:56", id: "dBcoGyxSSQ0", title: "Donatello - Maddalena penitente", tag: "Capolavori" },
    { time: "22:05", id: "oqTUTClIW2I", title: "Aristotele", tag: "Philosophia" },
    { time: "22:14", id: "bC_fklpuU38", title: "i consigli di Seneca - Tempo ed Equilibrio", tag: "Cultura classica" },
    { time: "22:23", id: "UMPd8bSHfKI", title: "I RACCONTI DI PLUTARCO - Vita di Cicerone - Infanzia e giovinezza", tag: "Cultura classica" },
    { time: "22:32", id: "Pkmfnn3KcWM", title: "Talete e l'acqua", tag: "Philosophia" },
    { time: "22:41", id: "ssqpvt30tw4", title: "ENEIDE - Enea racconta la caduta di Troia -  terza parte - LAOCOONTE", tag: "Eneide" },
    { time: "22:49", id: "PBQpaPQeVnk", title: "Vittore Crivelli - Polittico di Monte San Martino", tag: "Capolavori" },
    { time: "22:57", id: "s6QnfgVPxZA", title: "I simboli dell'alchimia nel Medioevo", tag: "Semeion" },
    { time: "23:05", id: "D0zSjqXl380", title: "Georges Braque - Violino", tag: "Capolavori" },
    { time: "23:13", id: "redrKZc2HoY", title: "I simboli dei Pellegrini nel Medioevo", tag: "Semeion" },
    { time: "23:21", id: "tH-9bTMomV8", title: "Francis Bacon - Studio per una corrida n°2", tag: "Capolavori" },
    { time: "23:29", id: "hEbi1jjkfak", title: "Oftalmoi - Il simbolo dell'occhio nell'Antica Grecia", tag: "Semeion" },
    { time: "23:37", id: "2hZy1rsXgj0", title: "Allegoria delle quattro Stagioni - Bartolomeo Manfredi", tag: "Simboli nell'Arte" },
    { time: "23:45", id: "-kT2WSjxw20", title: "L'ulivo, la civetta e il serpente - I Simboli e la Storia", tag: "Semeion" },
    { time: "23:53", id: "gc5RNyVXX-k", title: "Anathema ad Asclepio - I simboli nell'antica Grecia", tag: "Semeion" },
  ],
  3: [ // MERCOLEDI
    { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio delle trasmissioni", tag: "ARS EUROPA TV" },
    { time: "08:02", id: "EUKj2MyULiw", title: "Apocalisse: le ultime parole di Dio", tag: "Sacrum" },
    { time: "08:52", id: "V_G2rNyMWkA", title: "Vittore Crivelli - Trittico di Monte San Martino", tag: "Capolavori" },
    { time: "09:11", id: "gYZlbiG0Mk4", title: "Edipo a Colono - Sofocle", tag: "Teatro Greco" },
    { time: "10:00", id: "b0gBKKEZTA8", title: "L'usuraio, l'abate e la fanciulla", tag: "Decameron" },
    { time: "10:18", id: "-HHg7SoG04I", title: "Hugo van der Goes - Trittico Portinari", tag: "Capolavori" },
    { time: "10:51", id: "RxPRrZcmAuQ", title: "Domenico Ghirlandaio - Sacra conversazione degli Ingesuati", tag: "Capolavori" },
    { time: "11:09", id: "LBdvcDAlFjM", title: "Filottete  - Sofocle", tag: "Teatro Greco" },
    { time: "11:41", id: "PqT2h3bHqPY", title: "Simbologia del Ritratto dei coniugi Arnolfini - Jan van Eyck", tag: "Simboli nell'Arte" },
    { time: "11:58", id: "GrqPGuz1N-A", title: "Antigone - Sofocle", tag: "Teatro Greco" },
    { time: "12:28", id: "_l9LAjrgZl8", title: "Antonello da Messina - Ritratto d’uomo", tag: "Capolavori" },
    { time: "12:44", id: "7PHWv12rfXM", title: "SALVATORE QUASIMODO - Gli elementi della creazione -  I principi della Poesia", tag: "I principi della poesia" },
    { time: "13:13", id: "hboGN6-AvYo", title: "Seconda puntata - Simnoesi, pensare insieme, oltre lo specchio - Né Apocalittici né Integrati", tag: "Né Apocalittici né Integrati" },
    { time: "13:28", id: "9wxNflU3IFQ", title: "I Persiani -  Eschilo", tag: "Teatro Greco" },
    { time: "13:57", id: "T6_0Hzog4x0", title: "LUCA, lo scriba della mansuetudine", tag: "Tetramorfo" },
    { time: "14:12", id: "_YN4KrZiSjM", title: "Le Trachinie - Sofocle", tag: "Teatro Greco" },
    { time: "14:40", id: "-_OiF7-GR0Q", title: "Canto XIV - Inferno - Viaggio nell'Aldilà", tag: "Divina Commedia" },
    { time: "14:54", id: "2-MPaKWHva0", title: "Simbologia del Polittico dell'Agnello Mistico - Jan e Hubert van Eyck", tag: "Simboli nell'Arte" },
    { time: "15:22", id: "zrSkcpDgWuw", title: "La Cattedrale di Notre-Dame di Parigi", tag: "I luoghi, simboli e Storia" },
    { time: "15:35", id: "vGzv0sGe6F8", title: "Carlo Borromeo - Lo splendore dell'Umiltà", tag: "Historica" },
    { time: "16:00", id: "MAx6zDUILbQ", title: "Zenone e i suoi paradossi", tag: "Philosophia" },
    { time: "16:13", id: "SxTPMNST8Q4", title: "Le Supplici - Eschilo", tag: "Teatro Greco" },
    { time: "16:38", id: "8K6AO9ISUgc", title: "Allegoria del Cattivo Governo - Ambrogio Lorenzetti", tag: "Simboli nell'Arte" },
    { time: "16:51", id: "JBxkizfcJno", title: "Andreuccio da Perugia e la sorella ritrovata", tag: "Decameron" },
    { time: "17:15", id: "jid79a7Vzf0", title: "La simbologia delle insegne degli imperatori romani -  Antica Roma", tag: "Semeion" },
    { time: "17:28", id: "4O8X48ICIaw", title: "I sette contro Tebe - Eschilo", tag: "Teatro Greco" },
    { time: "17:51", id: "-4ahGMWqfM8", title: "Simbologia de La zattera della Medusa - Théodore Géricault", tag: "Simboli nell'Arte" },
    { time: "18:03", id: "YguWYzvu7Jk", title: "Giuffredi, il figlio della Capriola", tag: "Decameron" },
    { time: "18:23", id: "SOqN2uepscY", title: "Eraclito e il fuoco", tag: "Philosophia" },
    { time: "18:35", id: "wO56CDW3m-g", title: "Simbologia de La liberazione di san Pietro - Raffaello", tag: "Simboli nell'Arte" },
    { time: "18:47", id: "_n092qNIw7o", title: "La simbologia dello Scarabeo sacro nell'Antico Egitto", tag: "Semeion" },
    { time: "18:59", id: "3-Rc374qiAA", title: "Il matrimonio romano", tag: "Semeion" },
    { time: "19:11", id: "ElM7rPK06k8", title: "Come mandare il diavolo all'inferno", tag: "Decameron" },
    { time: "19:22", id: "Yxp4kXLBVsE", title: "Simbologia de La barca di Dante - Eugène Delacroix", tag: "Simboli nell'Arte" },
    { time: "19:33", id: "ysrwIZBk7jM", title: "Sofonisba Anguissola - Sposalizio mistico di Santa Caterina", tag: "Capolavori" },
    { time: "19:44", id: "mZHs1pTuSjU", title: "Simbologia dell'Annunciazione - Leonardo da Vinci", tag: "Simboli nell'Arte" },
    { time: "19:55", id: "EJcAT-aYu18", title: "Carlo e Vittore Crivelli - Polittico di Monte San Martino", tag: "Capolavori" },
    { time: "20:06", id: "5BJaK2Nv3L0", title: "Empedocle e i quattro elementi", tag: "Philosophia" },
    { time: "20:17", id: "aWlHf7nx3Z8", title: "San Giuliano, il mercante e la vedovella", tag: "Decameron" },
    { time: "20:28", id: "KvpEM4bgfZY", title: "Anassagora e il Nous", tag: "Philosophia" },
    { time: "20:39", id: "N5TveC0Jieo", title: "Cima da Conegliano - Sant'Elena", tag: "Capolavori" },
    { time: "20:50", id: "pqFlJHOibGI", title: "Democrito e gli atomi", tag: "Philosophia" },
    { time: "21:01", id: "33LYXRz6E5s", title: "Adone", tag: "Simboli, miti e leggende" },
    { time: "21:11", id: "La8RbJbSL6U", title: "Pitagora e i numeri", tag: "Philosophia" },
    { time: "21:21", id: "9BETjtp1mbA", title: "Parmenide e l'Essere", tag: "Philosophia" },
    { time: "21:31", id: "TjARMj13bPE", title: "Il corsaro Landolfo e la cassetta", tag: "Decameron" },
    { time: "21:41", id: "nIbmYCpuXDo", title: "Simbologia di Ambasciatori - Hans Holbein il Giovane", tag: "Simboli nell'Arte" },
    { time: "21:51", id: "owZDKzZtEMo", title: "Il mobile e la Storia", tag: "SIGN&DESIGN" },
    { time: "22:00", id: "8tkD5HhoxYM", title: "Chichibìo e la gru", tag: "Decameron" },
    { time: "22:09", id: "jeHmaJmp3wg", title: "Nehusthan, il serpente di bronzo", tag: "Storie dalla Bibbia" },
    { time: "22:17", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria", tag: "Philosophia" },
    { time: "22:25", id: "jNGOdGlE7LQ", title: "La Lupa - I Simboli e la Storia dell'Antica Roma", tag: "Semeion" },
    { time: "22:33", id: "MLF8Po4J-Yk", title: "I simboli e la Storia - Antica Roma - Le legioni", tag: "Semeion" },
    { time: "22:41", id: "h2SSOHy_LQg", title: "Erminio Avarizia", tag: "Decameron" },
    { time: "22:49", id: "4TXZ2pgdlb4", title: "ENEIDE - Enea racconta la caduta di Troia - seconda parte - SINONE", tag: "Eneide" },
    { time: "22:56", id: "HzIPvLDELVw", title: "I “signa”, le insegne militari dell'esercito romano - I Simboli e la Storia - Antica Roma", tag: "Semeion" },
    { time: "23:03", id: "U5HuJnOl12s", title: "I consigli di OVIDIO - il trucco femminile - ARS AMANDI", tag: "Cultura classica" },
    { time: "23:10", id: "JIDwzu-phUo", title: "I consigli di Marco Aurelio - cooperazione", tag: "Cultura classica" },
    { time: "23:17", id: "4JhzDRygmAI", title: "I consigli di CICERONE - il valore dell'amicizia - De Amicitia", tag: "Cultura classica" },
    { time: "23:24", id: "jtStIm5z7II", title: "I consigli di Seneca - Amicizia", tag: "Cultura classica" },
    { time: "23:31", id: "NGY1ZCjtirA", title: "L'egida, la capra Amaltea e la cornucopia - I simboli e la storia", tag: "Semeion" },
    { time: "23:37", id: "VVLf7kk3fo0", title: "I RACCONTI DI SALLUSTIO - la chiara fama", tag: "Cultura classica" },
    { time: "23:43", id: "ibNmDm7n1aQ", title: "I RACCONTI DI SALLUSTIO - la forza del corpo e il vigore dell'animo - la congiura di Catilina", tag: "Cultura classica" },
    { time: "23:49", id: "166JgZoFqjI", title: "I racconti di Sallustio - ritratto di Catilina", tag: "Cultura classica" },
    { time: "23:54", id: "XwVY9Wy6HaI", title: "I consigli di Seneca - il vero bene - LETTERE A LUCILIO", tag: "Cultura classica" },
    { time: "23:59", id: "NjNjIxWSz4w", title: "Gorgoneion - Le Gorgoni", tag: "Semeion" },
  ],
  4: [ // GIOVEDI
    { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio delle trasmissioni", tag: "ARS EUROPA TV" },
    { time: "08:02", id: "7_LUxivWuAM", title: "LE TROIANE - Euripide", tag: "Teatro Greco" },
    { time: "09:01", id: "xKRU6UqRLTQ", title: "Le Eumenidi - Eschilo", tag: "Teatro Greco" },
    { time: "09:20", id: "TNlYUDPzZtg", title: "ANDROMACA - Euripide", tag: "Teatro Greco" },
    { time: "10:10", id: "1zXxvYDhG4o", title: "Psiche", tag: "Simboli, miti e leggende" },
    { time: "10:28", id: "EhsO8Dea9yM", title: "ECUBA - Euripide", tag: "Teatro Greco" },
    { time: "11:16", id: "VzG3biTZ1rg", title: "Agamennone  -  Eschilo", tag: "Teatro Greco" },
    { time: "11:34", id: "NLPkp1cnsYE", title: "AMBROGIO, immortale", tag: "Historica" },
    { time: "12:19", id: "9jSQdHofi5c", title: "Terza puntata - L'Emittente nascosto - Né Apocalittici né Integrati", tag: "Né Apocalittici né Integrati" },
    { time: "12:36", id: "mwSAxNQ_re0", title: "Società dell'antica Roma - Semeion - 5ª puntata", tag: "Semeion" },
    { time: "13:16", id: "KIPYOCWYVSU", title: "GIOVANNI, lo sguardo dell'aquila", tag: "Tetramorfo" },
    { time: "13:33", id: "2eNrA0pvehA", title: "La sedia", tag: "SIGN&DESIGN" },
    { time: "14:11", id: "BqmMSIiR290", title: "Allegoria del Buon Governo - Ambrogio Lorenzetti", tag: "Simboli nell'Arte" },
    { time: "14:28", id: "H4YXia6yz-E", title: "Vita medievale - Semeion - 4ª puntata", tag: "Semeion" },
    { time: "15:05", id: "_33jtBhONO0", title: "Coefore - Eschilo", tag: "Teatro Greco" },
    { time: "15:22", id: "eX13aqoGOqU", title: "Il mito dei Fenici - Semeion - 7ª puntata", tag: "Semeion" },
    { time: "15:58", id: "UU9BLVei6QU", title: "L'occhio di Horus -  Antico Egitto", tag: "Semeion" },
    { time: "16:12", id: "hPWQR2BU49Y", title: "Religioni del Mediterraneo - Semeion - 6ª puntata", tag: "Semeion" },
    { time: "16:47", id: "AUwhHd-t-iw", title: "Simbologia nella Lotta tra Carnevale e Quaresima -  Pieter Brueghel il Vecchio", tag: "Simboli nell'Arte" },
    { time: "17:01", id: "bVVeeRVkKAE", title: "Montale e il male di vivere - la profezia del vuoto moderno", tag: "I principi della poesia" },
    { time: "17:32", id: "Vjes7xPZgo0", title: "Calandrino incinto", tag: "Decameron" },
    { time: "17:46", id: "tmyoBjeOX_g", title: "Misteri dell'antica Grecia - Semeion - 3ª puntata", tag: "Semeion" },
    { time: "18:17", id: "fdy6LJOROCI", title: "Canto XV - Inferno -Viaggio nell'Aldilà", tag: "Divina Commedia" },
    { time: "18:30", id: "_AHY1IOE1Hg", title: "I Demoni", tag: "Sacrum" },
    { time: "19:00", id: "Tuf5lu30V0M", title: "Pietro Cavallini - Giudizio Universale", tag: "Capolavori" },
    { time: "19:13", id: "BpfNVrGJreE", title: "Prometeo Incatenato - Eschilo", tag: "Teatro Greco" },
    { time: "19:38", id: "5D0qcufRzOw", title: "Bergamino e l'avarizia di Cangrande", tag: "Decameron" },
    { time: "19:51", id: "LIKOP__oc7I", title: "Giotto - Crocifisso di Padova", tag: "Capolavori" },
    { time: "20:14", id: "msTcwXQM3Qs", title: "GORGIA e la parola", tag: "Philosophia" },
    { time: "20:27", id: "5-BgoO5nwyM", title: "Andrea Mantegna - I trionfi di Giulio Cesare", tag: "Capolavori" },
    { time: "20:49", id: "zwMEiAsWU6c", title: "Cimabue - Crocifissione del transetto sinistro della Basilica Superiore di San Francesco", tag: "Capolavori" },
    { time: "21:02", id: "5coSTdhVpuU", title: "Platone", tag: "Philosophia" },
    { time: "21:15", id: "Bik77BxkBfM", title: "Beato Angelico - Giudizio Universale", tag: "Capolavori" },
    { time: "21:28", id: "YXKYiJ4vQjM", title: "Simbologia de IL  BACIO -  Francesco Hayez", tag: "Simboli nell'Arte" },
    { time: "21:41", id: "MYEi1LhYlo4", title: "PROTAGORA e le antilogie", tag: "Philosophia" },
    { time: "21:53", id: "odGTmKeuCMQ", title: "Cimabue - Maestà di Assisi", tag: "Capolavori" },
    { time: "22:05", id: "QcN8IL5cGiI", title: "Crisippo", tag: "Philosophia" },
    { time: "22:17", id: "auWg9IHeDb8", title: "La marchesa e le galline", tag: "Decameron" },
    { time: "22:27", id: "_57OfZukJTs", title: "Il Sultano Saladino e i tre anelli", tag: "Decameron" },
    { time: "22:37", id: "_noxbELcGdc", title: "Il Pantheon", tag: "I luoghi, simboli e Storia" },
    { time: "22:46", id: "PeDzAGHnkLw", title: "Il frate avido e la brodaglia dei poveri", tag: "Decameron" },
    { time: "22:55", id: "1zSwyFPn4Yk", title: "Socrate", tag: "Philosophia" },
    { time: "23:04", id: "UlL3gs7cSho", title: "I mosaici medievali e gli affreschi ottoniani della Cattedrale di Aosta", tag: "Simboli nell'Arte" },
    { time: "23:13", id: "mwBR1q1ezYM", title: "Piero del Pollaiolo - Pala del cardinale del Portogallo", tag: "Capolavori" },
    { time: "23:22", id: "oqTUTClIW2I", title: "Aristotele", tag: "Philosophia" },
    { time: "23:31", id: "xqulRBS-iIk", title: "Simbologia di GOLCONDA -  René Magritte", tag: "Simboli nell'Arte" },
    { time: "23:40", id: "TvY6zNfDhqo", title: "Debora e l'incontro di Sisara e Giaele", tag: "Storie dalla Bibbia" },
    { time: "23:48", id: "3pjCAAs55xo", title: "I consigli di CICERONE - Le forze nella vecchiaia", tag: "Cultura classica" },
    { time: "23:56", id: "0Q3UHX75roM", title: "I consigli di AGOSTINO - la felicità - le Confessioni", tag: "Cultura classica" },
  ],
  5: [ // VENERDI
    { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio delle trasmissioni", tag: "ARS EUROPA TV" },
    { time: "08:02", id: "XiZdP043an0", title: "Simbologia de LE STORIE DI CRISTO -  GIOTTO", tag: "Simboli nell'Arte" },
    { time: "09:07", id: "Dm5ND9wQNKk", title: "Quarta puntata - Antropotesi - Né Apocalittici né Integrati", tag: "Né Apocalittici né Integrati" },
    { time: "09:25", id: "vtJGNqiVUho", title: "IPPOLITO - Euripide", tag: "Teatro Greco" },
    { time: "10:17", id: "CKjDj0O-D4o", title: "ANTONIO, Abbà - L'eremita che inventò il monachesimo", tag: "Historica" },
    { time: "10:35", id: "gvBOqwT-iJ0", title: "Ifigenia in Aulide - Euripide", tag: "Teatro Greco" },
    { time: "11:21", id: "wStQPVyWzuM", title: "Ser Ciappelletto", tag: "Decameron" },
    { time: "11:39", id: "_5mO9eF7OzA", title: "IFIGENIA IN TAURIDE - Euripide", tag: "Teatro Greco" },
    { time: "12:22", id: "8RHc0dwAVmE", title: "Orfeo", tag: "Simboli, miti e leggende" },
    { time: "12:39", id: "S409sg6u1_M", title: "PIRANDELLO: una, nessuna, centomila maschere. E la tua qual è?", tag: "I principi della poesia" },
    { time: "13:19", id: "Brwji6geGWQ", title: "Matteo, la mano dell'angelo", tag: "Tetramorfo" },
    { time: "13:35", id: "297eGtKQnoA", title: "Carlo Magno Imperatore - Semeion - 2ª puntata", tag: "Semeion" },
    { time: "14:15", id: "GbXpfJo-Z6Y", title: "Piero della Francesca - I duchi di Urbino Federico da Montefeltro e Battista Sforza", tag: "Capolavori" },
    { time: "14:30", id: "Cn_F70P-77o", title: "Simbologia del Trittico delle Tentazioni di sant'Antonio di Hieronymus Bosch", tag: "Simboli nell'Arte" },
    { time: "15:06", id: "6yM8VKnx1D4", title: "Simbologia del GIUDIZIO UNIVERSALE - Giotto", tag: "Simboli nell'Arte" },
    { time: "15:21", id: "IjEmsqnsHKY", title: "L'invincibile esercito romano - Semeion - 1ª puntata", tag: "Semeion" },
    { time: "15:54", id: "dHmkQOcHcrY", title: "Il Colosseo", tag: "I luoghi, simboli e Storia" },
    { time: "16:08", id: "eSQcTSW5u50", title: "ALCESTI -  Euripide", tag: "Teatro Greco" },
    { time: "16:39", id: "Ukb7enwrhmU", title: "Martellino e il finto miracolo", tag: "Decameron" },
    { time: "16:52", id: "q8-VMJW1r80", title: "Il tavolo", tag: "SIGN&DESIGN" },
    { time: "17:22", id: "86HxQMkRBfo", title: "Le festività nell'antica Roma", tag: "Semeion" },
    { time: "17:35", id: "HkBxKcbf3hE", title: "TOBIOLO E L'ANGELO", tag: "Storie dalla Bibbia" },
    { time: "18:01", id: "p-GGCkdDG7o", title: "Canto XVI - Inferno - Viaggio nell'Aldilà", tag: "Divina Commedia" },
    { time: "18:13", id: "ktou5tayO18", title: "Simbologia del Giudizio Universale di Michelangelo", tag: "Simboli nell'Arte" },
    { time: "18:37", id: "w1nyMgzoZQE", title: "Enea racconta la caduta di Troia -  quarta parte - L'INCENDIO", tag: "Eneide" },
    { time: "18:49", id: "uaSEfOUDRDo", title: "Edipo re - Sofocle", tag: "Teatro Greco" },
    { time: "19:10", id: "egeEdEQFkT8", title: "Il monaco e l'abate", tag: "Decameron" },
    { time: "19:22", id: "zOEB44h7S5k", title: "Medea - Euripide", tag: "Teatro Greco" },
    { time: "19:42", id: "9K_bfj937Pg", title: "Un mercante ebreo in Vaticano", tag: "Decameron" },
    { time: "19:54", id: "SOqN2uepscY", title: "Eraclito e il fuoco", tag: "Philosophia" },
    { time: "20:06", id: "T9m9cm0dhWY", title: "Come attaccare la coda a una cavalla", tag: "Decameron" },
    { time: "20:18", id: "S80kNQbbpNk", title: "Anassimandro e l'apeiron", tag: "Philosophia" },
    { time: "20:29", id: "M7C3b1NSM7U", title: "La classe di danza di Edgar Degas", tag: "Capolavori" },
    { time: "20:40", id: "xLiWCB2m9Jg", title: "I simboli sacerdotali nell'antica Roma", tag: "Semeion" },
    { time: "20:51", id: "u1GPCMfYTbE", title: "Il Polittico di Giovanni Boccati nella Chiesa di Sant’Eustachio a Belforte del Chienti", tag: "Capolavori" },
    { time: "21:02", id: "uLLIhAn0DJM", title: "I simboli dei cavalieri medievali - Semeion, i Simboli e la Storia", tag: "Semeion" },
    { time: "21:13", id: "_RqV9r-Wm74", title: "Lo Spirito Santo nel Cristianesimo", tag: "Sacrum" },
    { time: "21:23", id: "ZPxrf6U1ygM", title: "Colijn de Coter - Polittico della Crocifissione - 1500 circa - Museo Nazionale Varsavia", tag: "Capolavori" },
    { time: "21:33", id: "La8RbJbSL6U", title: "Pitagora e i numeri", tag: "Philosophia" },
    { time: "21:43", id: "3DSXSrLUTqA", title: "Pignora imperii: i sette oggetti sacri di Roma", tag: "Semeion" },
    { time: "21:53", id: "9BETjtp1mbA", title: "Parmenide e l'Essere", tag: "Philosophia" },
    { time: "22:03", id: "h88VDynvAs0", title: "Maestro Alberto e il porro", tag: "Decameron" },
    { time: "22:12", id: "Pkmfnn3KcWM", title: "Talete e l'acqua", tag: "Philosophia" },
    { time: "22:21", id: "8tkD5HhoxYM", title: "Chichibìo e la gru", tag: "Decameron" },
    { time: "22:30", id: "ITdd3pc_Yu0", title: "Simbologia di GUERNICA  -  Pablo Picasso", tag: "Simboli nell'Arte" },
    { time: "22:38", id: "Q0NFO2Cs93U", title: "Anassimene e l'aria", tag: "Philosophia" },
    { time: "22:46", id: "7cNggvoR4PM", title: "Simone Martini e Lippo Memmi - Annunciazione e i santi Ansano e Massima - Uffizi", tag: "Capolavori" },
    { time: "22:54", id: "K1vFnkYUA6c", title: "I simboli dei sottufficiali romani", tag: "Semeion" },
    { time: "23:01", id: "Cy1rxcIA3ZY", title: "I consigli di PLATONE - l'ALDILA' e il giudizio", tag: "Cultura classica" },
    { time: "23:08", id: "xeHuZbgtj6M", title: "I consigli di CICERONE -- le aspettative", tag: "Cultura classica" },
    { time: "23:15", id: "gawFAzVeAto", title: "i consigli di Seneca - la Filosofia", tag: "Cultura classica" },
    { time: "23:22", id: "0ftfDKWeYS0", title: "I consigli di OVIDIO - agli uomini - ARS AMANDI", tag: "Cultura classica" },
    { time: "23:29", id: "3aA0vZ2GOgA", title: "Simbologia di NOTTE STELLATA -  Vincent Van Gogh", tag: "Simboli nell'Arte" },
    { time: "23:35", id: "_UBPKd5YdI0", title: "I consigli di AGOSTINO - l'oroscopo e le previsioni astrologiche", tag: "Cultura classica" },
    { time: "23:41", id: "CvAgf2Ma_L0", title: "I consigli di Seneca - La sobrietà - Lettere a Lucilio", tag: "Cultura classica" },
    { time: "23:47", id: "lBnP772e7AA", title: "I consigli di PLATONE - le buone discussioni", tag: "Cultura classica" },
    { time: "23:52", id: "MbRcDJGh3DI", title: "Tintoretto - Crocifissione", tag: "Capolavori" },
    { time: "23:57", id: "HQqdZ18-UHA", title: "Giacomo Leopardi - L'Infinito", tag: "Poesia" },
  ],
  6: [ // SABATO
    { time: "08:00", id: "nRrWSTaabeQ", title: "Inizio delle trasmissioni", tag: "ARS EUROPA TV" },
    { time: "08:02", id: "EUKj2MyULiw", title: "Apocalisse: le ultime parole di Dio", tag: "Sacrum" },
    { time: "08:52", id: "b0gBKKEZTA8", title: "L'usuraio, l'abate e la fanciulla", tag: "Decameron" },
    { time: "09:10", id: "gYZlbiG0Mk4", title: "Edipo a Colono - Sofocle", tag: "Teatro Greco" },
    { time: "09:59", id: "djHOf0ETZjk", title: "Quinta puntata - il racconto senza storia - Né Apocalittici né Integrati", tag: "Né Apocalittici né Integrati" },
    { time: "10:15", id: "JxHiv1EbEXY", title: "Aiace - Sofocle", tag: "Teatro Greco" },
    { time: "10:58", id: "hIJjgqUb-8I", title: "Simbologia del TONDO DONI  - Michelangelo", tag: "Simboli nell'Arte" },
    { time: "11:13", id: "51ko0maD8pY", title: "Simbologia delle \"Très Riches Heures du Duc de Berry\" -  FRATELLI LIMBOURG", tag: "Simboli nell'Arte" },
    { time: "11:54", id: "vf7owO-7PgY", title: "Simbologia de LA MADONNA DEL MAGNIFICAT -  Sandro Botticelli", tag: "Simboli nell'Arte" },
    { time: "12:09", id: "jJpr7Ttffks", title: "Dante Alighieri - Tra terra e cielo - I principi della poesia", tag: "I principi della poesia" },
    { time: "12:47", id: "dKTmwGpxC9g", title: "Canto XVII - Inferno - Viaggio nell'Aldilà", tag: "Divina Commedia" },
    { time: "13:01", id: "VNx-F7naSK0", title: "ELETTRA -  Sofocle", tag: "Teatro Greco" },
    { time: "13:39", id: "gTKMLCt9YYo", title: "Adorazione dei Magi di Gentile da Fabriano", tag: "Simboli nell'Arte" },
    { time: "13:53", id: "dly0X-1e3bo", title: "Il letto", tag: "SIGN&DESIGN" },
    { time: "14:27", id: "OIbMcxEIubc", title: "Giovanni di Paolo - Madonna col Bambino e Santi - Creazione e Cacciata dal Paradiso Terrestre", tag: "Capolavori" },
    { time: "14:41", id: "LBdvcDAlFjM", title: "Filottete  - Sofocle", tag: "Teatro Greco" },
    { time: "15:13", id: "nji3BUHv_Fs", title: "MARCO, il leone della fede", tag: "Tetramorfo" },
    { time: "15:26", id: "GrqPGuz1N-A", title: "Antigone - Sofocle", tag: "Teatro Greco" },
    { time: "15:56", id: "zrSkcpDgWuw", title: "La Cattedrale di Notre-Dame di Parigi", tag: "I luoghi, simboli e Storia" },
    { time: "16:09", id: "9wxNflU3IFQ", title: "I Persiani -  Eschilo", tag: "Teatro Greco" },
    { time: "16:38", id: "5DtPo9q0YJo", title: "VALENTINO, un amore trascendente", tag: "Historica" },
    { time: "16:51", id: "_YN4KrZiSjM", title: "Le Trachinie - Sofocle", tag: "Teatro Greco" },
    { time: "17:19", id: "MAx6zDUILbQ", title: "Zenone e i suoi paradossi", tag: "Philosophia" },
    { time: "17:32", id: "XfFiEQ2preg", title: "Giotto - Storie di San Francesco - Parte 3di3", tag: "Simboli nell'Arte" },
    { time: "17:59", id: "msTcwXQM3Qs", title: "GORGIA e la parola", tag: "Philosophia" },
    { time: "18:12", id: "JBxkizfcJno", title: "Andreuccio da Perugia e la sorella ritrovata", tag: "Decameron" },
    { time: "18:36", id: "YT6KLLfPhSQ", title: "Louis Janmot - Il Poema dell'Anima", tag: "Capolavori" },
    { time: "18:48", id: "0UOJdSzhFrI", title: "Teti", tag: "Simboli, miti e leggende" },
    { time: "19:08", id: "MYEi1LhYlo4", title: "PROTAGORA e le antilogie", tag: "Philosophia" },
    { time: "19:20", id: "YguWYzvu7Jk", title: "Giuffredi, il figlio della Capriola", tag: "Decameron" },
    { time: "19:40", id: "ElM7rPK06k8", title: "Come mandare il diavolo all'inferno", tag: "Decameron" },
    { time: "19:51", id: "xCTDCGDexz4", title: "Jacopo di Cione - Polittico di San Pier Maggiore", tag: "Capolavori" },
    { time: "20:11", id: "5BJaK2Nv3L0", title: "Empedocle e i quattro elementi", tag: "Philosophia" },
    { time: "20:22", id: "KvpEM4bgfZY", title: "Anassagora e il Nous", tag: "Philosophia" },
    { time: "20:33", id: "pqFlJHOibGI", title: "Democrito e gli atomi", tag: "Philosophia" },
    { time: "20:44", id: "aWlHf7nx3Z8", title: "San Giuliano, il mercante e la vedovella", tag: "Decameron" },
    { time: "20:55", id: "eTdJ1nws6yw", title: "Simbologia de IL BACCHINO MALATO -  Caravaggio", tag: "Simboli nell'Arte" },
    { time: "21:05", id: "bimuhQ5N6Wg", title: "Margarito d’Arezzo - Madonna col Bambino in Trono", tag: "Capolavori" },
    { time: "21:15", id: "E3bNrJqqvjQ", title: "Amuleti e talismani nell'antica Roma", tag: "Semeion" },
    { time: "21:25", id: "TjARMj13bPE", title: "Il corsaro Landolfo e la cassetta", tag: "Decameron" },
    { time: "21:35", id: "bSIeXu1fmZw", title: "Simbologia dell'abbigliamento maschile nell'antica Roma", tag: "Semeion" },
    { time: "21:45", id: "kL2UrUxrfWY", title: "Maestro Olandese o della Germania Settentrionale - Trittico di Gerusalemme", tag: "Simboli nell'Arte" },
    { time: "21:54", id: "1oMoXawAhUs", title: "Il serpente nell'antica Grecia", tag: "Semeion" },
    { time: "22:03", id: "bC_fklpuU38", title: "i consigli di Seneca - Tempo ed Equilibrio", tag: "Cultura classica" },
    { time: "22:12", id: "UMPd8bSHfKI", title: "I RACCONTI DI PLUTARCO - Vita di Cicerone - Infanzia e giovinezza", tag: "Cultura classica" },
    { time: "22:21", id: "JgZfs2eImmg", title: "Vittore Crivelli - Polittico di San Severino", tag: "Capolavori" },
    { time: "22:30", id: "1zSwyFPn4Yk", title: "Socrate", tag: "Philosophia" },
    { time: "22:39", id: "ssqpvt30tw4", title: "ENEIDE - Enea racconta la caduta di Troia -  terza parte - LAOCOONTE", tag: "Eneide" },
    { time: "22:47", id: "7Y3g-9sAX2g", title: "Il segno del comando nell'Antica Roma", tag: "Semeion" },
    { time: "22:55", id: "EVNS93JNpUM", title: "I simboli nei mosaici romani", tag: "Semeion" },
    { time: "23:03", id: "y93e6we2ceo", title: "I simboli sugli scudi nell'Antica Grecia", tag: "Semeion" },
    { time: "23:11", id: "h2SSOHy_LQg", title: "Erminio Avarizia", tag: "Decameron" },
    { time: "23:19", id: "BLDB2zuKUhA", title: "ELISEO, la vedova e l'olio", tag: "Storie dalla Bibbia" },
    { time: "23:26", id: "AxePQgHrhC8", title: "I consigli di Marco Aurelio - La percezione", tag: "Cultura classica" },
    { time: "23:33", id: "se06EQ6E364", title: "San Girolamo nello studio di Antonello da Messina", tag: "Capolavori" },
    { time: "23:40", id: "VVLf7kk3fo0", title: "I RACCONTI DI SALLUSTIO - la chiara fama", tag: "Cultura classica" },
    { time: "23:46", id: "VlLgbobv-Ec", title: "Claude Monet - Il mare agitato a Étretat", tag: "Capolavori" },
    { time: "23:51", id: "WgNzIFn9CU4", title: "I RACCONTI DI PLUTARCO - la fine di Romolo", tag: "Cultura classica" },
    { time: "23:56", id: "166JgZoFqjI", title: "I racconti di Sallustio - ritratto di Catilina", tag: "Cultura classica" },
  ],
};
